# Makefile: Makefile to compile MFB Transformer
# Copyright (C) 2020 CESNET
# Author: Tomas Hak <xhakto01@stud.fit.vutbr.cz>

TOP_LEVEL_ENT=MFB_REGION_RECONFIGURATOR

# SYNTH=quartus
#
# export CLK_PERIOD=4.0
# export DEVICE=ULTRASCALE
#
.PHONY: all
all: comp

include ../../../../../../../build/Makefile
