# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=FLU_ASFIFO_LUT

CLK_PORTS=RX_CLK TX_CLK
CLK_PERIOD=4 5

.PHONY: all
all: comp

include ../../../../../build/Makefile
