# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Mario Kuka <kuka@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DMA_HDR_EXTRACTOR

CLK_PERIOD=2.5

.PHONY: all
all: comp
include ../../../../../build/Makefile
