# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Vladislav Valek <xvalek14@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=SR_SYNC_LATCH

SYNTH=vivado
export CLK_PERIOD=2.64
export DEVICE=ULTRASCALE

all: comp
include ../../../../../build/Makefile
.PHONY: all
