// trim_sequences.sv: Collection of sequences that generate trim data based on the length of data frames
// Copyright (C) 2025 CESNET z. s. p. o.
// Author(s): Yaroslav Marushchenko <xmarus09@stud.fit.vutbr.cz>
// SPDX-License-Identifier: BSD-3-Clause

virtual class trim_sequence_length_base #(int unsigned BLOCK_SIZE, int unsigned ITEM_WIDTH, int unsigned META_WIDTH, int unsigned PKT_MTU) extends uvm_logic_vector::sequence_simple #(META_WIDTH+1+$clog2(PKT_MTU+1));
    `uvm_object_param_utils(test::trim_sequence_length_base #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU))
    `m_uvm_get_type_name_func(test::trim_sequence_length_base)

    localparam int unsigned MIN_LENGTH = (BLOCK_SIZE*ITEM_WIDTH)-(ITEM_WIDTH-1);

    rand int unsigned transaction_count;

    // Stores the lengths of data frames generated by an RX MFB data sequence
    mailbox #(int unsigned) mfb_item_lengths;

    // Constructor
    function new(string name = "trim_sequence_length_base");
        super.new(name);
    endfunction

    // Gets a `mfb_item_lengths` mailbox reference from the database
    function void load_from_db();
        assert(uvm_config_db #(mailbox #(int unsigned))::get(m_sequencer, "", "mfb_item_lengths", mfb_item_lengths))
        else begin
            `uvm_fatal(m_sequencer.get_full_name(), "Cannot get a mfb_item_lengths mailbox")
        end
    endfunction

    // Generates transactions
    pure virtual task body;

endclass

class trim_sequence_random_length #(int unsigned BLOCK_SIZE, int unsigned ITEM_WIDTH, int unsigned META_WIDTH, int unsigned PKT_MTU) extends trim_sequence_length_base #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU);
    `uvm_object_param_utils(test::trim_sequence_random_length #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU))
    `m_uvm_get_type_name_func(test::trim_sequence_random_length)

    int unsigned transaction_count_min = 30;
    int unsigned transaction_count_max = 45;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "trim_sequence_random_length");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        int unsigned mfb_item_length;

        load_from_db();

        repeat (transaction_count) begin
            mfb_item_lengths.get(mfb_item_length);

            // Generate random request
            if (mfb_item_length > MIN_LENGTH) begin
                `uvm_do_with(req, {
                    // RX_TRIM_LEN
                    req.data[$clog2(PKT_MTU+1)-1 -: $clog2(PKT_MTU+1)] >= MIN_LENGTH;
                    req.data[$clog2(PKT_MTU+1)-1 -: $clog2(PKT_MTU+1)] < mfb_item_length;
                })
            end
            else begin
                `uvm_do_with(req, {
                    // RX_TRIM_EN
                    req.data[1+$clog2(PKT_MTU+1)-1 -: 1] == 1'b0;
                })
            end
        end
    endtask

endclass

class trim_sequence_original_length #(int unsigned BLOCK_SIZE, int unsigned ITEM_WIDTH, int unsigned META_WIDTH, int unsigned PKT_MTU) extends trim_sequence_length_base #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU);
    `uvm_object_param_utils(test::trim_sequence_original_length #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU))
    `m_uvm_get_type_name_func(test::trim_sequence_original_length)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 45;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "trim_sequence_original_length");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        int unsigned mfb_item_length;

        load_from_db();

        repeat (transaction_count) begin
            mfb_item_lengths.get(mfb_item_length);

            // Generate random request
            if (mfb_item_length > MIN_LENGTH) begin
                `uvm_do_with(req, {
                    // RX_TRIM_EN
                    req.data[1+$clog2(PKT_MTU+1)-1 -: 1] == 1'b1;
                    // RX_TRIM_LEN
                    req.data[$clog2(PKT_MTU+1)-1 -: $clog2(PKT_MTU+1)] == mfb_item_length;
                })
            end
            else begin
                `uvm_do_with(req, {
                    // RX_TRIM_EN
                    req.data[1+$clog2(PKT_MTU+1)-1 -: 1] == 1'b0;
                })
            end
        end
    endtask

endclass

class trim_sequence_minimal_length #(int unsigned BLOCK_SIZE, int unsigned ITEM_WIDTH, int unsigned META_WIDTH, int unsigned PKT_MTU) extends trim_sequence_length_base #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU);
    `uvm_object_param_utils(test::trim_sequence_minimal_length #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU))
    `m_uvm_get_type_name_func(test::trim_sequence_minimal_length)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 45;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "trim_sequence_minimal_length");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        int unsigned mfb_item_length;

        load_from_db();

        repeat (transaction_count) begin
            mfb_item_lengths.get(mfb_item_length);

            // Generate random request
            if (mfb_item_length > MIN_LENGTH) begin
                `uvm_do_with(req, {
                    // RX_TRIM_EN
                    req.data[1+$clog2(PKT_MTU+1)-1 -: 1] == 1'b1;
                    // RX_TRIM_LEN
                    req.data[$clog2(PKT_MTU+1)-1 -: $clog2(PKT_MTU+1)] == MIN_LENGTH;
                })
            end
            else begin
                `uvm_do_with(req, {
                    // RX_TRIM_EN
                    req.data[1+$clog2(PKT_MTU+1)-1 -: 1] == 1'b0;
                })
            end
        end
    endtask

endclass

class trim_sequence_library #(int unsigned BLOCK_SIZE, int unsigned ITEM_WIDTH, int unsigned META_WIDTH, int unsigned PKT_MTU) extends uvm_common::sequence_library #(uvm_logic_vector::config_sequence, uvm_logic_vector::sequence_item #(META_WIDTH+1+$clog2(PKT_MTU+1)));
    `uvm_object_param_utils(test::trim_sequence_library #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU))
    `uvm_sequence_library_utils(test::trim_sequence_library #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU))

    function new(string name = "trim_sequence_library");
        super.new(name);

        init_sequence_library();
    endfunction

    virtual function void init_sequence(uvm_logic_vector::config_sequence param_cfg = null);
        super.init_sequence(param_cfg);

        this.add_sequence(trim_sequence_random_length   #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU)::get_type());
        this.add_sequence(trim_sequence_original_length #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU)::get_type());
        this.add_sequence(trim_sequence_minimal_length  #(BLOCK_SIZE, ITEM_WIDTH, META_WIDTH, PKT_MTU)::get_type());
    endfunction

endclass
