# Makefile: Makefile script to compile specified module
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Oliver Gurka <oliver.gurka@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MP_BRAM

SYNTH=quartus
DEVICE=AGILEX
CLK_PORTS=CLK
CLK_PERIOD=4.1 3

.PHONY: all
all: comp

include ../../../../../build/Makefile
