# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ETH_AVST_ADAPTER_SHAKEDOWN


SYNTH=quartus

.PHONY: all
all: comp

include ../../../../../../../../../build/Makefile
