-- SPDX-License-Identifier: BSD-3-Clause
-- Copyright (C) 2026 CESNET z. s. p. o
-- Author(s): Ondrej Schwarz <ondrejschwarz@cesnet.cz>

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.math_pack.all;
use work.type_pack.all;

-- 1D celluar automaton with repeating border rules
-- component of the PCASD hash algorithm.
entity PCASD_CA_ROUND is
    generic (
        -- width of the celluar automaton
        STATE_WIDTH : natural   := 256;
        -- width of the passthrough metadata
        META_WIDTH  : natural   := 32;
        -- setup of the registers of this component
        OUT_REG     : boolean := true
    );
    port (
        -- main clock
        CLK         : in  std_logic;
        -- synchronious reset
        RESET       : in  std_logic;
        -- start state of the celluar automaton
        IN_STATE    : in  unsigned(STATE_WIDTH-1 downto 0);
        -- celluar automaton rule input
        IN_RULE     : in  unsigned(8-1 downto 0);
        -- seed passthrough input
        IN_SEED     : in  unsigned(128-1 downto 0);
        -- metadata passthrough input
        IN_META     : in  std_logic_vector(META_WIDTH-1 downto 0);
        -- validity of input
        IN_VALID    : in  std_logic;

        -- new state of the celluar automaton
        OUT_STATE   : out unsigned(STATE_WIDTH-1 downto 0);
        -- celluar automaton rule passthrough output
        OUT_RULE    : out unsigned(8-1 downto 0);
        -- seed passthrough output
        OUT_SEED    : out unsigned(128-1 downto 0);
        -- metadata passthrough output
        OUT_META    : out std_logic_vector(META_WIDTH-1 downto 0);
        -- valid passthrough
        OUT_VALID   : out std_logic
    );
end entity;

architecture FULL of PCASD_CA_ROUND is
    -- new state generated by applying the CA rule
    signal new_state : unsigned(STATE_WIDTH-1 downto 0);
    -- index of the bit of the rule that is set as the new state
    signal bit_index : u_array_t(STATE_WIDTH-1 downto 0)(3-1 downto 0);

begin
    -- ================================================
    --                     LOGIC
    -- ================================================

    -- generating the parallel celluar automaton
    ca_g: for g in STATE_WIDTH-1 downto 0 generate
        -- establishing the index of the bit of the rule
        -- that is set as the new state based on three
        -- adjecent bits of the current state
        bit_index(g)(2) <= IN_STATE((g + 1) mod STATE_WIDTH);
        bit_index(g)(1) <= IN_STATE(g);
        bit_index(g)(0) <= IN_STATE((g - 1) mod STATE_WIDTH);

        new_state(g) <= IN_RULE(to_integer(bit_index(g)));
    end generate;

    -- ================================================
    --                     OUTPUT
    -- ================================================
    out_reg_g: if OUT_REG generate

        process (CLK)
        begin
            if rising_edge(CLK) then
                OUT_STATE <= new_state;
                OUT_RULE  <= IN_RULE;
                OUT_SEED  <= IN_SEED;
                OUT_META  <= IN_META;
                OUT_VALID <= IN_VALID;

                if (RESET = '1') then
                    OUT_VALID <= '0';
                end if;
            end if;
        end process;

    else generate
        OUT_STATE <= new_state;
        OUT_RULE  <= IN_RULE;
        OUT_SEED  <= IN_SEED;
        OUT_META  <= IN_META;
        OUT_VALID <= IN_VALID;
    end generate;

end architecture;
