# Makefile: Makefile script to compile specified module
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Vladislav Válek <valekv@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=TX_DMA_PKT_DISPATCHER

#SYNTH=quartus
#DEVICE=AGILEX
CLK_PORTS=CLK
CLK_PERIOD=4

.PHONY: all
all: comp

include ../../../../../../../../build/Makefile
