# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DP_BRAM_BEHAV

CLK_PORTS=CLKA CLKB
CLK_PERIOD=4.000 3.000

.PHONY: all
all: comp

include ../../../../../build/Makefile
