# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=FLUA_BINDER

CLK_PORTS=MI_CLK RX_CLK XLGMII_TXCLK
CLK_PERIOD=5.000 5.000 6.333

.PHONY: all
all: comp

include ../../../../../../../build/Makefile
