# Makefile: Synthesis Makefile
# Copyright (C) 2024 DynaNIC Semiconductors, Ltd.
# Author(s): Radek Hajek <hajek@dyna-nic.com>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MFB2AXI

.PHONY: all
all: comp

include ../../../../../build/Makefile
