# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DP_BRAM_V7

CLK_PORTS=CLKA CLKB
CLK_PERIOD=5 4

.PHONY: all
all: comp

include ../../../../../build/Makefile
