# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#

TOP_LEVEL_ENT=TX_MAC_LITE_ADAPTER_LBUS
#SYNTH=quartus
export CLK_PERIOD=2.500
#export DEVICE=ULT.RASCALE
#export DEVICE=AGILEX

all: comp
include ../../../../../../../../build/Makefile
.PHONY: all
