# Makefile: Makefile to compile MFB Transformer
# Copyright (C) 2020 CESNET
# Author: Tomas Hak <xhakto01@stud.fit.vutbr.cz>

TOP_LEVEL_ENT=MFB_TRANSFORMER

#SYNTH=quartus

#CLK_PERIOD=4.0
#DEVICE=ULTRASCALE

.PHONY: all
all: comp

include ../../../../../build/Makefile
