# Makefile: Makefile to compile single module
# Copyright (C) 2025 CESNET z. s. p. o.
# Author(s): Tomas Hak <hak@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXIS_SWITCH
TOP_LEVEL_PATH=../../
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../../../build/Makefile
