# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MVB_MERGE_ITEMS
SYNTH=quartus

.PHONY: all
all: comp

include ../../../../../build/Makefile
