# Makefile: Makefile script to compile specified module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DSP_COUNTER_STRATIX_10_ATOM

SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=STRATIX10

all: comp
include ../../../../../../../build/Makefile
.PHONY: all
