# pcie.xdc:
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

set_property PACKAGE_PIN AL1     [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN AL2     [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN AM3     [get_ports {PCIE_RX_N[1]}]
set_property PACKAGE_PIN AM4     [get_ports {PCIE_RX_P[1]}]
set_property PACKAGE_PIN AN5     [get_ports {PCIE_RX_N[2]}]
set_property PACKAGE_PIN AN6     [get_ports {PCIE_RX_P[2]}]
set_property PACKAGE_PIN AN1     [get_ports {PCIE_RX_N[3]}]
set_property PACKAGE_PIN AN2     [get_ports {PCIE_RX_P[3]}]
set_property PACKAGE_PIN AP3     [get_ports {PCIE_RX_N[4]}]
set_property PACKAGE_PIN AP4     [get_ports {PCIE_RX_P[4]}]
set_property PACKAGE_PIN AR1     [get_ports {PCIE_RX_N[5]}]
set_property PACKAGE_PIN AR2     [get_ports {PCIE_RX_P[5]}]
set_property PACKAGE_PIN AT3     [get_ports {PCIE_RX_N[6]}]
set_property PACKAGE_PIN AT4     [get_ports {PCIE_RX_P[6]}]
set_property PACKAGE_PIN AU1     [get_ports {PCIE_RX_N[7]}]
set_property PACKAGE_PIN AU2     [get_ports {PCIE_RX_P[7]}]
set_property PACKAGE_PIN AV3     [get_ports {PCIE_RX_N[8]}]
set_property PACKAGE_PIN AV4     [get_ports {PCIE_RX_P[8]}]
set_property PACKAGE_PIN AW5     [get_ports {PCIE_RX_N[9]}]
set_property PACKAGE_PIN AW6     [get_ports {PCIE_RX_P[9]}]
set_property PACKAGE_PIN AW1     [get_ports {PCIE_RX_N[10]}]
set_property PACKAGE_PIN AW2     [get_ports {PCIE_RX_P[10]}]
set_property PACKAGE_PIN AY3     [get_ports {PCIE_RX_N[11]}]
set_property PACKAGE_PIN AY4     [get_ports {PCIE_RX_P[11]}]
set_property PACKAGE_PIN BA5     [get_ports {PCIE_RX_N[12]}]
set_property PACKAGE_PIN BA6     [get_ports {PCIE_RX_P[12]}]
set_property PACKAGE_PIN BA1     [get_ports {PCIE_RX_N[13]}]
set_property PACKAGE_PIN BA2     [get_ports {PCIE_RX_P[13]}]
set_property PACKAGE_PIN BB3     [get_ports {PCIE_RX_N[14]}]
set_property PACKAGE_PIN BB4     [get_ports {PCIE_RX_P[14]}]
set_property PACKAGE_PIN BC1     [get_ports {PCIE_RX_N[15]}]
set_property PACKAGE_PIN BC2     [get_ports {PCIE_RX_P[15]}]

set_property PACKAGE_PIN AL10    [get_ports {PCIE_TX_N[0]}]
set_property PACKAGE_PIN AL11    [get_ports {PCIE_TX_P[0]}]
set_property PACKAGE_PIN AM8     [get_ports {PCIE_TX_N[1]}]
set_property PACKAGE_PIN AM9     [get_ports {PCIE_TX_P[1]}]
set_property PACKAGE_PIN AN10    [get_ports {PCIE_TX_N[2]}]
set_property PACKAGE_PIN AN11    [get_ports {PCIE_TX_P[2]}]
set_property PACKAGE_PIN AP8     [get_ports {PCIE_TX_N[3]}]
set_property PACKAGE_PIN AP9     [get_ports {PCIE_TX_P[3]}]
set_property PACKAGE_PIN AR10    [get_ports {PCIE_TX_N[4]}]
set_property PACKAGE_PIN AR11    [get_ports {PCIE_TX_P[4]}]
set_property PACKAGE_PIN AR6     [get_ports {PCIE_TX_N[5]}]
set_property PACKAGE_PIN AR7     [get_ports {PCIE_TX_P[5]}]
set_property PACKAGE_PIN AT8     [get_ports {PCIE_TX_N[6]}]
set_property PACKAGE_PIN AT9     [get_ports {PCIE_TX_P[6]}]
set_property PACKAGE_PIN AU10    [get_ports {PCIE_TX_N[7]}]
set_property PACKAGE_PIN AU11    [get_ports {PCIE_TX_P[7]}]
set_property PACKAGE_PIN AU6     [get_ports {PCIE_TX_N[8]}]
set_property PACKAGE_PIN AU7     [get_ports {PCIE_TX_P[8]}]
set_property PACKAGE_PIN AV8     [get_ports {PCIE_TX_N[9]}]
set_property PACKAGE_PIN AV9     [get_ports {PCIE_TX_P[9]}]
set_property PACKAGE_PIN AW10    [get_ports {PCIE_TX_N[10]}]
set_property PACKAGE_PIN AW11    [get_ports {PCIE_TX_P[10]}]
set_property PACKAGE_PIN AY8     [get_ports {PCIE_TX_N[11]}]
set_property PACKAGE_PIN AY9     [get_ports {PCIE_TX_P[11]}]
set_property PACKAGE_PIN BA10    [get_ports {PCIE_TX_N[12]}]
set_property PACKAGE_PIN BA11    [get_ports {PCIE_TX_P[12]}]
set_property PACKAGE_PIN BB8     [get_ports {PCIE_TX_N[13]}]
set_property PACKAGE_PIN BB9     [get_ports {PCIE_TX_P[13]}]
set_property PACKAGE_PIN BC10    [get_ports {PCIE_TX_N[14]}]
set_property PACKAGE_PIN BC11    [get_ports {PCIE_TX_P[14]}]
set_property PACKAGE_PIN BC6     [get_ports {PCIE_TX_N[15]}]
set_property PACKAGE_PIN BC7     [get_ports {PCIE_TX_P[15]}]

set_property PACKAGE_PIN BF41    [get_ports {PCIE_SYSRST_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {PCIE_SYSRST_N}]
set_property PULLUP true         [get_ports {PCIE_SYSRST_N}]

set_property PACKAGE_PIN AL15    [get_ports {PCIE_SYSCLK0_P}]
set_property PACKAGE_PIN AL14    [get_ports {PCIE_SYSCLK0_N}]

set_property PACKAGE_PIN AR15    [get_ports {PCIE_SYSCLK1_P}]
set_property PACKAGE_PIN AR14    [get_ports {PCIE_SYSCLK1_N}]

create_clock -period 10.000 -name pcie_clk0_p -waveform {0.000 5.000} [get_ports {PCIE_SYSCLK0_P}]
create_clock -period 10.000 -name pcie_clk1_p -waveform {0.000 5.000} [get_ports {PCIE_SYSCLK1_P}]

