# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Daniel Kondys <kondys@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=FRAME_UNPACKER
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE
# export DEVICE=AGILEX

all: comp
include ../../../../../build/Makefile
.PHONY: all

