# Makefile: General width MVB MUX
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Oliver Gurka <xgurka00@stud.fit.vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MVB_MUX2
SYNTH=quartus

export CLK_PERIOD=6.0
export DEVICE=STRATIX10

all: comp

include ../../../../../../ofm/build/Makefile

.PHONY: all
