# Makefile: Makefile script to compile specified module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Lukas Kekely <kekely@cesnet.cz>
#

TOP_LEVEL_ENT=MFB_FORK

all: comp

include ../../../../../build/Makefile

.PHONY: all
