# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s):Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=tsu_gen
#SYNTH=quartus

#DEVICE=STRATIX10
CLK_PORTS=CLK MI_CLK

all: comp

include ../../../../build/Makefile

.PHONY: all
