# Makefile: Makefile script to compile specified module
# Copyright (C) 2024 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=HBM_TESTER
SYNTH=quartus

export CLK_PERIOD=2.5
export DEVICE=AGILEX

all: comp

include ../../../../../build/Makefile

.PHONY: all
