# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=CMP_DSP

SYNTH=vivado
#export CLK_PERIOD=4.0
#export DEVICE=AGILEX

all: comp
include ../../../../../../../build/Makefile
.PHONY: all
