// sequencer_length_extractor.sv: Reveals the lengths of generated RX MFB data frames
// Copyright (C) 2025 CESNET z. s. p. o.
// Author(s): Yaroslav Marushchenko <xmarus09@stud.fit.vutbr.cz>
// SPDX-License-Identifier: BSD-3-Clause

class sequencer_length_extractor #(int unsigned MFB_ITEM_WIDTH) extends uvm_logic_vector_array::sequencer #(MFB_ITEM_WIDTH);
    `uvm_component_param_utils(uvm_mfb_frame_extender::sequencer_length_extractor #(MFB_ITEM_WIDTH))

    // Stores the lengths of data frames generated by an RX MFB data sequence
    mailbox #(int unsigned) frame_lengths;

    function new(string name = "sequencer_length_extractor", uvm_component parent = null);
        super.new(name, parent);

        frame_lengths = new();
    endfunction

    task try_next_item(output uvm_logic_vector_array::sequence_item #(ITEM_WIDTH) t);
        super.try_next_item(t);
        if (t === null) begin
            return;
        end
        // Put the data frame length
        frame_lengths.put(t.size());
    endtask

endclass
