# Makefile: Makefile script to compile specified module
# Copyright (C) 2018 CESNET z. s. p. o.
# Author(s): Martin Spinler <spinler@cesnet.cz>

TOP_LEVEL_ENT=FLU_BINDER
#SYNTH=quartus

#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

all: comp

.PHONY: all

include ../../../../../build/Makefile
