# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#

TOP_LEVEL_ENT=mgmt
#SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE
#export DEVICE=AGILEX

all: comp
include ../../../../../../build/Makefile
.PHONY: all
