# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=TX_MAC_LITE_ADDR_DEC
SYNTH=quartus

CLK_PORTS=CLK MI_CLK

all: comp
include ../../../../../../../build/Makefile
.PHONY: all
