# ddr4.xdc
# Copyright (C) 2022 CESNET z.s.p.o.
# Author(s): David Beneš <xbenes52@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

# DDR4A interface
# Internal Clocks
set_property PACKAGE_PIN BA34 [get_ports DDR4A_REFCLK_P]
set_property PACKAGE_PIN BB34 [get_ports DDR4A_REFCLK_N]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports [list DDR4A_REFCLK_*]]
set_property ODT RTT_48 [get_ports [list DDR4A_REFCLK_*]]

#General Pins
set_property PACKAGE_PIN BD34 [get_ports {DDR4A_A[0]}]
set_property PACKAGE_PIN AV33 [get_ports {DDR4A_A[1]}]
set_property PACKAGE_PIN AM32 [get_ports {DDR4A_A[2]}]
set_property PACKAGE_PIN AL34 [get_ports {DDR4A_A[3]}]
set_property PACKAGE_PIN BE35 [get_ports {DDR4A_A[4]}]
set_property PACKAGE_PIN AY33 [get_ports {DDR4A_A[5]}]
set_property PACKAGE_PIN AY35 [get_ports {DDR4A_A[6]}]
set_property PACKAGE_PIN AW33 [get_ports {DDR4A_A[7]}]
set_property PACKAGE_PIN AW34 [get_ports {DDR4A_A[8]}]
set_property PACKAGE_PIN AU34 [get_ports {DDR4A_A[9]}]
set_property PACKAGE_PIN AN34 [get_ports {DDR4A_A[10]}]
set_property PACKAGE_PIN BC34 [get_ports {DDR4A_A[11]}]
set_property PACKAGE_PIN BE36 [get_ports {DDR4A_A[12]}]
set_property PACKAGE_PIN AL32 [get_ports {DDR4A_A[13]}]
set_property PACKAGE_PIN BB37 [get_ports {DDR4A_A[14]}]
set_property PACKAGE_PIN AM34 [get_ports {DDR4A_A[15]}]
set_property PACKAGE_PIN AP33 [get_ports {DDR4A_A[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_A[*]]

set_property PACKAGE_PIN AY36 [get_ports {DDR4A_BA[0]}]
set_property PACKAGE_PIN BA33 [get_ports {DDR4A_BA[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_BA[*]]

set_property PACKAGE_PIN AV34 [get_ports {DDR4A_CKE[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_CKE[*]]

set_property PACKAGE_PIN AP34 [get_ports {DDR4A_CS_N[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_CS_N]

set_property PACKAGE_PIN AA32 [get_ports {DDR4A_LDM[0]}]
set_property PACKAGE_PIN AH34 [get_ports {DDR4A_LDM[1]}]
set_property PACKAGE_PIN AP31 [get_ports {DDR4A_LDM[2]}]
set_property PACKAGE_PIN BC31 [get_ports {DDR4A_LDM[3]}]
set_property IOSTANDARD POD12_DCI [get_ports DDR4A_LDM[*]]

set_property PACKAGE_PIN AE31 [get_ports {DDR4A_UDM[0]}]
set_property PACKAGE_PIN AJ27 [get_ports {DDR4A_UDM[1]}]
set_property PACKAGE_PIN AW29 [get_ports {DDR4A_UDM[2]}]
set_property PACKAGE_PIN BF32 [get_ports {DDR4A_UDM[3]}]
set_property IOSTANDARD POD12_DCI [get_ports DDR4A_UDM[*]]

set_property PACKAGE_PIN Y33  [get_ports {DDR4A_DQ[0]}]
set_property PACKAGE_PIN W34  [get_ports {DDR4A_DQ[1]}]
set_property PACKAGE_PIN AA34 [get_ports {DDR4A_DQ[2]}]
set_property PACKAGE_PIN Y32  [get_ports {DDR4A_DQ[3]}]
set_property PACKAGE_PIN W33  [get_ports {DDR4A_DQ[4]}]
set_property PACKAGE_PIN W30  [get_ports {DDR4A_DQ[5]}]
set_property PACKAGE_PIN AB34 [get_ports {DDR4A_DQ[6]}]
set_property PACKAGE_PIN Y30  [get_ports {DDR4A_DQ[7]}]
set_property PACKAGE_PIN AD33 [get_ports {DDR4A_DQ[8]}]
set_property PACKAGE_PIN AC34 [get_ports {DDR4A_DQ[9]}]
set_property PACKAGE_PIN AE33 [get_ports {DDR4A_DQ[10]}]
set_property PACKAGE_PIN AC33 [get_ports {DDR4A_DQ[11]}]
set_property PACKAGE_PIN AF30 [get_ports {DDR4A_DQ[12]}]
set_property PACKAGE_PIN AC32 [get_ports {DDR4A_DQ[13]}]
set_property PACKAGE_PIN AE30 [get_ports {DDR4A_DQ[14]}]
set_property PACKAGE_PIN AD34 [get_ports {DDR4A_DQ[15]}]
set_property PACKAGE_PIN AF34 [get_ports {DDR4A_DQ[16]}]
set_property PACKAGE_PIN AJ33 [get_ports {DDR4A_DQ[17]}]
set_property PACKAGE_PIN AG34 [get_ports {DDR4A_DQ[18]}]
set_property PACKAGE_PIN AG32 [get_ports {DDR4A_DQ[19]}]
set_property PACKAGE_PIN AF33 [get_ports {DDR4A_DQ[20]}]
set_property PACKAGE_PIN AG31 [get_ports {DDR4A_DQ[21]}]
set_property PACKAGE_PIN AF32 [get_ports {DDR4A_DQ[22]}]
set_property PACKAGE_PIN AH33 [get_ports {DDR4A_DQ[23]}]
set_property PACKAGE_PIN AK31 [get_ports {DDR4A_DQ[24]}]
set_property PACKAGE_PIN AK28 [get_ports {DDR4A_DQ[25]}]
set_property PACKAGE_PIN AJ31 [get_ports {DDR4A_DQ[26]}]
set_property PACKAGE_PIN AJ29 [get_ports {DDR4A_DQ[27]}]
set_property PACKAGE_PIN AG29 [get_ports {DDR4A_DQ[28]}]
set_property PACKAGE_PIN AJ28 [get_ports {DDR4A_DQ[29]}]
set_property PACKAGE_PIN AG30 [get_ports {DDR4A_DQ[30]}]
set_property PACKAGE_PIN AJ30 [get_ports {DDR4A_DQ[31]}]
set_property PACKAGE_PIN AP29 [get_ports {DDR4A_DQ[32]}]
set_property PACKAGE_PIN AM31 [get_ports {DDR4A_DQ[33]}]
set_property PACKAGE_PIN AN31 [get_ports {DDR4A_DQ[34]}]
set_property PACKAGE_PIN AL30 [get_ports {DDR4A_DQ[35]}]
set_property PACKAGE_PIN AP30 [get_ports {DDR4A_DQ[36]}]
set_property PACKAGE_PIN AL29 [get_ports {DDR4A_DQ[37]}]
set_property PACKAGE_PIN AR30 [get_ports {DDR4A_DQ[38]}]
set_property PACKAGE_PIN AN29 [get_ports {DDR4A_DQ[39]}]
set_property PACKAGE_PIN AW31 [get_ports {DDR4A_DQ[40]}]
set_property PACKAGE_PIN AV32 [get_ports {DDR4A_DQ[41]}]
set_property PACKAGE_PIN AV31 [get_ports {DDR4A_DQ[42]}]
set_property PACKAGE_PIN AU31 [get_ports {DDR4A_DQ[43]}]
set_property PACKAGE_PIN AU30 [get_ports {DDR4A_DQ[44]}]
set_property PACKAGE_PIN AU32 [get_ports {DDR4A_DQ[45]}]
set_property PACKAGE_PIN AT29 [get_ports {DDR4A_DQ[46]}]
set_property PACKAGE_PIN AT30 [get_ports {DDR4A_DQ[47]}]
set_property PACKAGE_PIN AY32 [get_ports {DDR4A_DQ[48]}]
set_property PACKAGE_PIN BB29 [get_ports {DDR4A_DQ[49]}]
set_property PACKAGE_PIN AY30 [get_ports {DDR4A_DQ[50]}]
set_property PACKAGE_PIN BB31 [get_ports {DDR4A_DQ[51]}]
set_property PACKAGE_PIN BA30 [get_ports {DDR4A_DQ[52]}]
set_property PACKAGE_PIN BB30 [get_ports {DDR4A_DQ[53]}]
set_property PACKAGE_PIN AY31 [get_ports {DDR4A_DQ[54]}]
set_property PACKAGE_PIN BA29 [get_ports {DDR4A_DQ[55]}]
set_property PACKAGE_PIN BC29 [get_ports {DDR4A_DQ[56]}]
set_property PACKAGE_PIN BF30 [get_ports {DDR4A_DQ[57]}]
set_property PACKAGE_PIN BD33 [get_ports {DDR4A_DQ[58]}]
set_property PACKAGE_PIN BE30 [get_ports {DDR4A_DQ[59]}]
set_property PACKAGE_PIN BD29 [get_ports {DDR4A_DQ[60]}]
set_property PACKAGE_PIN BE31 [get_ports {DDR4A_DQ[61]}]
set_property PACKAGE_PIN BE33 [get_ports {DDR4A_DQ[62]}]
set_property PACKAGE_PIN BE32 [get_ports {DDR4A_DQ[63]}]
set_property IOSTANDARD POD12_DCI[ get_ports DDR4A_DQ[*] ]

set_property PACKAGE_PIN Y31  [get_ports {DDR4A_LDQS_N[0]}]
set_property PACKAGE_PIN AH32 [get_ports {DDR4A_LDQS_N[1]}]
set_property PACKAGE_PIN AM30 [get_ports {DDR4A_LDQS_N[2]}]
set_property PACKAGE_PIN BB32 [get_ports {DDR4A_LDQS_N[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4A_LDQS_N[*]]

set_property PACKAGE_PIN W31  [get_ports {DDR4A_LDQS_P[0]}]
set_property PACKAGE_PIN AH31 [get_ports {DDR4A_LDQS_P[1]}]
set_property PACKAGE_PIN AM29 [get_ports {DDR4A_LDQS_P[2]}]
set_property PACKAGE_PIN BA32 [get_ports {DDR4A_LDQS_P[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4A_LDQS_P[*]]

set_property PACKAGE_PIN AD31 [get_ports {DDR4A_UDQS_N[0]}]
set_property PACKAGE_PIN AH29 [get_ports {DDR4A_UDQS_N[1]}]
set_property PACKAGE_PIN AV29 [get_ports {DDR4A_UDQS_N[2]}]
set_property PACKAGE_PIN BD31 [get_ports {DDR4A_UDQS_N[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4A_UDQS_N[*]]

set_property PACKAGE_PIN AC31 [get_ports {DDR4A_UDQS_P[0]}]
set_property PACKAGE_PIN AH28 [get_ports {DDR4A_UDQS_P[1]}]
set_property PACKAGE_PIN AU29 [get_ports {DDR4A_UDQS_P[2]}]
set_property PACKAGE_PIN BD30 [get_ports {DDR4A_UDQS_P[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4A_UDQS_P[*]]

set_property PACKAGE_PIN BD35 [get_ports {DDR4A_ODT[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_ODT*]

set_property PACKAGE_PIN AW36 [get_ports {DDR4A_BG[0]}]
set_property PACKAGE_PIN AR33 [get_ports {DDR4A_BG[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_BG[*]]

set_property PACKAGE_PIN AW35 [get_ports DDR4A_RESET_N]
set_property IOSTANDARD LVCMOS12 [get_ports DDR4A_RESET_N]
set_property DRIVE 8 [get_ports DDR4A_RESET_N]

set_property PACKAGE_PIN AL33 [get_ports DDR4A_ACT_N]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4A_ACT_N]

set_property PACKAGE_PIN AN33 [get_ports {DDR4A_CK_N[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports DDR4A_CK_N[*]]

set_property PACKAGE_PIN AN32 [get_ports {DDR4A_CK_P[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports DDR4A_CK_P[*]]

set_property PACKAGE_PIN BD36 [get_ports DDR4A_TEN]
set_property IOSTANDARD LVCMOS12 [get_ports DDR4A_TEN]
 
#DDR4B interface
# Internal Clocks
set_property PACKAGE_PIN C36 [get_ports DDR4B_REFCLK_P]
set_property PACKAGE_PIN C37 [get_ports DDR4B_REFCLK_N]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports [list DDR4B_REFCLK_*]]
set_property ODT RTT_48 [get_ports [list DDR4B_REFCLK_*]]

#General Pins
set_property PACKAGE_PIN E37 [get_ports {DDR4B_A[0]}]
set_property PACKAGE_PIN D36 [get_ports {DDR4B_A[1]}]
set_property PACKAGE_PIN E36 [get_ports {DDR4B_A[2]}]
set_property PACKAGE_PIN B35 [get_ports {DDR4B_A[3]}]
set_property PACKAGE_PIN D35 [get_ports {DDR4B_A[4]}]
set_property PACKAGE_PIN C32 [get_ports {DDR4B_A[5]}]
set_property PACKAGE_PIN D39 [get_ports {DDR4B_A[6]}]
set_property PACKAGE_PIN D33 [get_ports {DDR4B_A[7]}]
set_property PACKAGE_PIN E40 [get_ports {DDR4B_A[8]}]
set_property PACKAGE_PIN E35 [get_ports {DDR4B_A[9]}]
set_property PACKAGE_PIN A38 [get_ports {DDR4B_A[10]}]
set_property PACKAGE_PIN E39 [get_ports {DDR4B_A[11]}]
set_property PACKAGE_PIN B37 [get_ports {DDR4B_A[12]}]
set_property PACKAGE_PIN D31 [get_ports {DDR4B_A[13]}]
set_property PACKAGE_PIN B39 [get_ports {DDR4B_A[14]}]
set_property PACKAGE_PIN C31 [get_ports {DDR4B_A[15]}]
set_property PACKAGE_PIN B31 [get_ports {DDR4B_A[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_A[*]]

set_property PACKAGE_PIN D40 [get_ports {DDR4B_BA[0]}]
set_property PACKAGE_PIN B32 [get_ports {DDR4B_BA[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_BA[*]]

set_property PACKAGE_PIN C33 [get_ports {DDR4B_CKE[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_CKE[*]]

set_property PACKAGE_PIN A37 [get_ports {DDR4B_CS_N[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_CS_N]

set_property PACKAGE_PIN C27 [get_ports {DDR4B_LDM[0]}]
set_property PACKAGE_PIN M29 [get_ports {DDR4B_LDM[1]}]
set_property PACKAGE_PIN G30 [get_ports {DDR4B_LDM[2]}]
set_property PACKAGE_PIN R30 [get_ports {DDR4B_LDM[3]}]
set_property IOSTANDARD POD12_DCI [get_ports DDR4B_LDM[*]]

set_property PACKAGE_PIN J26 [get_ports {DDR4B_UDM[0]}]
set_property PACKAGE_PIN T28 [get_ports {DDR4B_UDM[1]}]
set_property PACKAGE_PIN M31 [get_ports {DDR4B_UDM[2]}]
set_property PACKAGE_PIN U34 [get_ports {DDR4B_UDM[3]}]
set_property IOSTANDARD POD12_DCI [get_ports DDR4B_UDM[*]]

set_property PACKAGE_PIN B30 [get_ports {DDR4B_DQ[0]}]
set_property PACKAGE_PIN C29 [get_ports {DDR4B_DQ[1]}]
set_property PACKAGE_PIN B29 [get_ports {DDR4B_DQ[2]}]
set_property PACKAGE_PIN A29 [get_ports {DDR4B_DQ[3]}]
set_property PACKAGE_PIN A30 [get_ports {DDR4B_DQ[4]}]
set_property PACKAGE_PIN D29 [get_ports {DDR4B_DQ[5]}]
set_property PACKAGE_PIN E30 [get_ports {DDR4B_DQ[6]}]
set_property PACKAGE_PIN D30 [get_ports {DDR4B_DQ[7]}]
set_property PACKAGE_PIN H29 [get_ports {DDR4B_DQ[8]}]
set_property PACKAGE_PIN E28 [get_ports {DDR4B_DQ[9]}]
set_property PACKAGE_PIN G29 [get_ports {DDR4B_DQ[10]}]
set_property PACKAGE_PIN G27 [get_ports {DDR4B_DQ[11]}]
set_property PACKAGE_PIN E27 [get_ports {DDR4B_DQ[12]}]
set_property PACKAGE_PIN D28 [get_ports {DDR4B_DQ[13]}]
set_property PACKAGE_PIN G26 [get_ports {DDR4B_DQ[14]}]
set_property PACKAGE_PIN F27 [get_ports {DDR4B_DQ[15]}]
set_property PACKAGE_PIN J28 [get_ports {DDR4B_DQ[16]}]
set_property PACKAGE_PIN L28 [get_ports {DDR4B_DQ[17]}]
set_property PACKAGE_PIN J29 [get_ports {DDR4B_DQ[18]}]
set_property PACKAGE_PIN L27 [get_ports {DDR4B_DQ[19]}]
set_property PACKAGE_PIN H28 [get_ports {DDR4B_DQ[20]}]
set_property PACKAGE_PIN M27 [get_ports {DDR4B_DQ[21]}]
set_property PACKAGE_PIN H27 [get_ports {DDR4B_DQ[22]}]
set_property PACKAGE_PIN K28 [get_ports {DDR4B_DQ[23]}]
set_property PACKAGE_PIN N28 [get_ports {DDR4B_DQ[24]}]
set_property PACKAGE_PIN R27 [get_ports {DDR4B_DQ[25]}]
set_property PACKAGE_PIN P28 [get_ports {DDR4B_DQ[26]}]
set_property PACKAGE_PIN T27 [get_ports {DDR4B_DQ[27]}]
set_property PACKAGE_PIN P26 [get_ports {DDR4B_DQ[28]}]
set_property PACKAGE_PIN R26 [get_ports {DDR4B_DQ[29]}]
set_property PACKAGE_PIN N26 [get_ports {DDR4B_DQ[30]}]
set_property PACKAGE_PIN T26 [get_ports {DDR4B_DQ[31]}]
set_property PACKAGE_PIN F33 [get_ports {DDR4B_DQ[32]}]
set_property PACKAGE_PIN G32 [get_ports {DDR4B_DQ[33]}]
set_property PACKAGE_PIN H32 [get_ports {DDR4B_DQ[34]}]
set_property PACKAGE_PIN E32 [get_ports {DDR4B_DQ[35]}]
set_property PACKAGE_PIN F32 [get_ports {DDR4B_DQ[36]}]
set_property PACKAGE_PIN G31 [get_ports {DDR4B_DQ[37]}]
set_property PACKAGE_PIN E33 [get_ports {DDR4B_DQ[38]}]
set_property PACKAGE_PIN H31 [get_ports {DDR4B_DQ[39]}]
set_property PACKAGE_PIN L33 [get_ports {DDR4B_DQ[40]}]
set_property PACKAGE_PIN J31 [get_ports {DDR4B_DQ[41]}]
set_property PACKAGE_PIN L32 [get_ports {DDR4B_DQ[42]}]
set_property PACKAGE_PIN K33 [get_ports {DDR4B_DQ[43]}]
set_property PACKAGE_PIN M30 [get_ports {DDR4B_DQ[44]}]
set_property PACKAGE_PIN K32 [get_ports {DDR4B_DQ[45]}]
set_property PACKAGE_PIN L30 [get_ports {DDR4B_DQ[46]}]
set_property PACKAGE_PIN K31 [get_ports {DDR4B_DQ[47]}]
set_property PACKAGE_PIN N33 [get_ports {DDR4B_DQ[48]}]
set_property PACKAGE_PIN R31 [get_ports {DDR4B_DQ[49]}]
set_property PACKAGE_PIN N34 [get_ports {DDR4B_DQ[50]}]
set_property PACKAGE_PIN P34 [get_ports {DDR4B_DQ[51]}]
set_property PACKAGE_PIN N32 [get_ports {DDR4B_DQ[52]}]
set_property PACKAGE_PIN R32 [get_ports {DDR4B_DQ[53]}]
set_property PACKAGE_PIN N31 [get_ports {DDR4B_DQ[54]}]
set_property PACKAGE_PIN P31 [get_ports {DDR4B_DQ[55]}]
set_property PACKAGE_PIN U31 [get_ports {DDR4B_DQ[56]}]
set_property PACKAGE_PIN U30 [get_ports {DDR4B_DQ[57]}]
set_property PACKAGE_PIN T32 [get_ports {DDR4B_DQ[58]}]
set_property PACKAGE_PIN V31 [get_ports {DDR4B_DQ[59]}]
set_property PACKAGE_PIN T30 [get_ports {DDR4B_DQ[60]}]
set_property PACKAGE_PIN T33 [get_ports {DDR4B_DQ[61]}]
set_property PACKAGE_PIN R33 [get_ports {DDR4B_DQ[62]}]
set_property PACKAGE_PIN U32 [get_ports {DDR4B_DQ[63]}]
set_property IOSTANDARD POD12_DCI [get_ports DDR4B_DQ[*]]

set_property PACKAGE_PIN A28 [get_ports {DDR4B_LDQS_N[0]}]
set_property PACKAGE_PIN K27 [get_ports {DDR4B_LDQS_N[1]}]
set_property PACKAGE_PIN H33 [get_ports {DDR4B_LDQS_N[2]}]
set_property PACKAGE_PIN L34 [get_ports {DDR4B_LDQS_N[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4B_LDQS_N[*]]

set_property PACKAGE_PIN A27 [get_ports {DDR4B_LDQS_P[0]}]
set_property PACKAGE_PIN K26 [get_ports {DDR4B_LDQS_P[1]}]
set_property PACKAGE_PIN J33 [get_ports {DDR4B_LDQS_P[2]}]
set_property PACKAGE_PIN M34 [get_ports {DDR4B_LDQS_P[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4B_LDQS_P[*]]

set_property PACKAGE_PIN F29 [get_ports {DDR4B_UDQS_N[0]}]
set_property PACKAGE_PIN N29 [get_ports {DDR4B_UDQS_N[1]}]
set_property PACKAGE_PIN J30 [get_ports {DDR4B_UDQS_N[2]}]
set_property PACKAGE_PIN V33 [get_ports {DDR4B_UDQS_N[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4B_UDQS_N[*]]

set_property PACKAGE_PIN F28 [get_ports {DDR4B_UDQS_P[0]}]
set_property PACKAGE_PIN P29 [get_ports {DDR4B_UDQS_P[1]}]
set_property PACKAGE_PIN K30 [get_ports {DDR4B_UDQS_P[2]}]
set_property PACKAGE_PIN V32 [get_ports {DDR4B_UDQS_P[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports DDR4B_UDQS_P[*]]

set_property PACKAGE_PIN C34 [get_ports {DDR4B_ODT[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_ODT*]

set_property PACKAGE_PIN B40 [get_ports {DDR4B_BG[0]}]
set_property PACKAGE_PIN B36 [get_ports {DDR4B_BG[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_BG[*]]

set_property PACKAGE_PIN D34 [get_ports DDR4B_RESET_N]
set_property IOSTANDARD LVCMOS12 [get_ports DDR4B_RESET_N]
set_property DRIVE 8 [get_ports DDR4B_RESET_N]

set_property PACKAGE_PIN A40 [get_ports DDR4B_ACT_N]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4B_ACT_N]

set_property PACKAGE_PIN A33 [get_ports {DDR4B_CK_N[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports DDR4B_CK_N[*]]

set_property PACKAGE_PIN A32 [get_ports {DDR4B_CK_P[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports DDR4B_CK_P[*]]

set_property PACKAGE_PIN A35 [get_ports DDR4B_TEN]
set_property IOSTANDARD LVCMOS12 [get_ports DDR4B_TEN]
