#!/bin/python3

#  SPDX-License-Identifier: BSD-3-Clause
#
#  simple pakcet generator. Packet are generated by random walk.
#
#  Copyright (C) 2022 CESNET
#  Author(s):
#    Radek Iša <isa@cesnet.cz>


def json_object_get(json, path):
    index = 0
    obj   = json
    while index < len(path) and obj is not None:
        obj = obj.get(path[index])
        index += 1

    return obj


class packet_config:
    def __init__(self, constraints=None):
        #init values
        self.trill   = 1
        self.vlan    = 4
        self.mpls    = 4
        self.ipv6ext = 4

        self.constraints = constraints

        mpls_stack = self.object_get(["mpls", "stack"])
        if mpls_stack is not None:
            self.mpls = int(mpls_stack.get("max"))

        vlan_stack = self.object_get(["vlan", "stack"])
        if vlan_stack is not None:
            self.vlan = int(vlan_stack.get("max"))

        ipv6ext_stack = self.object_get(["ipv6ext", "stack"])
        if ipv6ext_stack is not None:
            pass
            # self.ipv6ext = int(ipv6ext.get("max"))

    def copy(self):
        ret = packet_config(self.constraints)
        ret.trill   = self.trill
        ret.vlan    = self.vlan
        ret.mpls    = self.mpls
        ret.ipv6ext = self.ipv6ext
        return ret

    def object_get(self, path):
        return json_object_get(self.constraints, path)
