# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Vladislav Valek <xvalek14@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=RX_DMA_CALYPTE_TRANS_BUFFER
TOP_LEVEL_PATH=..

SYNTH=vivado

CLK_PORTS=CLK
CLK_PERIOD=4

.PHONY: all
all: comp

include ../../../../../../../../build/Makefile
