# Makefile: Makefile to compile module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=TX_MAC_LITE_ADAPTER_MAC_SEG
SYNTH=quartus
export CLK_PERIOD=2.5
#export DEVICE=ULTRASCALE

all: comp
include ../../../../../../../../build/Makefile
.PHONY: all
