# Makefile: Makefile to compile module
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Daniel Kondys <kondys@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=PPR_REQUEST_PROCESSOR
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../../build/Makefile
