# Makefile: Makefile to compile module
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Oliver Gurka <oliver.gurka@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MVB_OPERATION
SYNTH=quartus

.PHONY: all
all: comp

include ../../../../../build/Makefile
