# Makefile: Makefile to compile module
# Copyright (C) 2026 CESNET z.s.p.o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MFB_GET_LAST_ITEMS

.PHONY: all
all: comp

include ../../../../../build/Makefile
