# Modules.tcl: Components include script
# Copyright (C) DynaNIC Semiconductors, Ltd.
# Author(s): Vlastimil Kosar <kosar@dyna-nic.com>, 2025
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXIS_PIPE

SYNTH=vivado
#export CLK_PERIOD=20.0
export DEVICE=VERSAL

.PHONY: all
all: comp

include ../../../../../build/Makefile
