# Makefile: Makefile to compile module
# Copyright (C) 2020 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#

TOP_LEVEL_ENT=CROSSBARX_STREAM
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

all: comp
include ../../../../../build/Makefile
.PHONY: all
