# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#

TOP_LEVEL_ENT=N_ONE

SYNTH=quartus
export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

all: comp
include ../../../../../build/Makefile
.PHONY: all
