# Makefile: Makefile script to compile specified module
# Copyright (C) 2020 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#

TOP_LEVEL_ENT=MTC
#SYNTH=quartus

export CLK_PERIOD=4.0
#export DEVICE=STRATIX10

all: comp

include ../../../../build/Makefile

.PHONY: all
