# Makefile: Makefile to compile module
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MFB_PD_ASFIFO_SIMPLE
SYNTH=quartus

CLK_PORTS=RX_CLK TX_CLK
CLK_PERIOD=5.0 4.0

.PHONY: all
all: comp

include ../../../../../build/Makefile
