# Makefile: Synthesis Makefile
# Copyright (C) 2024 BrnoLogic, Ltd.
# Author(s): Radek Hajek <hajek@brnologic.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXI2MFB

.PHONY: all
all: comp

include ../../../../../build/Makefile
