# Makefile: Makefile script to compile specified module
# Copyright (C) 2020 CESNET z. s. p. o.
# Author(s): Vladislav Valek <xvalek14@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=PULSE_SHORT

export CLK_PERIOD=2.56

all: comp
include ../../../../../build/Makefile
.PHONY: all
