# Makefile: Makefile to compile module
# Copyright (C) 2024 CESNET
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXIS_PACKET_CONCATENATOR

SYNTH=quartus
export DEVICE=AGILEX

.PHONY: all
all: comp

include ../../../../../build/Makefile
