# Makefile: Makefile script to compile specified module
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Daniel Kondys <kondys@cesnet.cz>
#

TOP_LEVEL_ENT=PPR_REQUEST_PROCESSOR
SYNTH=quartus

#export CLK_PERIOD=4.0
#export DEVICE=STRATIX10

all: comp

include ../../../../../../build/Makefile

.PHONY: all
