# ver_settings.py
# Copyright (C) 2020 CESNET z. s. p. o.
# Author(s): Daniel Kříž <xkrizd01@vutbr.cz>

SETTINGS = {
    "default" : { # The default setting of verification
        "OUTPUT_PORTS"      : "2",
        "REGIONS"           : "4",
        "REGION_SIZE"       : "8",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "8",
        "META_WIDTH"        : "2",
        "USE_DST_RDY"       : "1",
        "VERSION"           : "\\\"logic\\\"",
        "FRAME_SIZE_MAX"    : "512",
        "FRAME_SIZE_MIN"    : "60",
        "TRANSACTION_COUNT" : "1000",
    },
    "pcie" : {
        "REGIONS"           : "2",
        "REGION_SIZE"       : "1",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "32",
    },
    "region_comb_1" : {
        "REGIONS"           : "4",
        "REGION_SIZE"       : "8",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "8",
    },
    "region_comb_2" : {
        "REGIONS"           : "2",
        "REGION_SIZE"       : "8",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "8",
    },
    "region_comb_3" : {
        "REGIONS"           : "1",
        "REGION_SIZE"       : "1",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "8",
    },
    "region_comb_4" : {
        "REGIONS"           : "1",
        "REGION_SIZE"       : "2",
        "BLOCK_SIZE"        : "4",
        "ITEM_WIDTH"        : "8",
    },
    "region_comb_5" : {
        "REGIONS"           : "1",
        "REGION_SIZE"       : "2",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "8",
    },
    "region_comb_6" : {
        "REGIONS"           : "1",
        "REGION_SIZE"       : "4",
        "BLOCK_SIZE"        : "8",
        "ITEM_WIDTH"        : "8",
    },
    "version_register" : {
        "VERSION"           : "\\\"register\\\"",
    },
    "version_simple" : {
        "VERSION"           : "\\\"simple\\\"",
    },
    "use_dst_rdy_0" : {
        "USE_DST_RDY"       : "0",
    },
    "4_output_ports" : {
        "OUTPUT_PORTS"      : "4",
    },
    "8_output_ports" : {
        "OUTPUT_PORTS"      : "8",
    },
    "medium_frames" : {
        "FRAME_SIZE_MIN"    : "2048",
        "FRAME_SIZE_MAX"    : "4096",
        "ITEM_WIDTH"        : "16",
        "META_WIDTH"        : "16",
    },
    "small_frames" : {
        "FRAME_SIZE_MIN"    : "32",
        "FRAME_SIZE_MAX"    : "512",
        "ITEM_WIDTH"        : "8",
        "META_WIDTH"        : "8",
    },
    "_combinations_" : (
    (), # Works the same as '("default",),' as the "default" is applied in every combination
    ("region_comb_1",),
    ("region_comb_2",),
    ("region_comb_3",),
    ("region_comb_4",),
    ("region_comb_5",),
    ("region_comb_6",),
    ("pcie",),
    ("version_register",),
    ("version_simple",),

    ("pcie","version_simple","use_dst_rdy_0",),
    ("pcie","version_register","use_dst_rdy_0",),
    ("pcie","use_dst_rdy_0",),

    ("region_comb_1","version_register",),
    ("region_comb_1","version_register","4_output_ports",),
    ("region_comb_1","version_register","8_output_ports"),
    ("region_comb_1","version_simple",),
    ("region_comb_1","version_simple","4_output_ports",),
    ("region_comb_1","version_simple","8_output_ports"),
    ("region_comb_1","4_output_ports",),
    ("region_comb_1","8_output_ports"),

    ("region_comb_2","version_register",),
    ("region_comb_2","version_register","4_output_ports",),
    ("region_comb_2","version_register","8_output_ports"),
    ("region_comb_2","version_simple",),
    ("region_comb_2","version_simple","4_output_ports",),
    ("region_comb_2","version_simple","8_output_ports"),
    ("region_comb_2","4_output_ports",),
    ("region_comb_2","8_output_ports"),

    ("region_comb_3","version_register",),
    ("region_comb_3","version_register","4_output_ports",),
    ("region_comb_3","version_register","8_output_ports"),
    ("region_comb_3","version_simple",),
    ("region_comb_3","version_simple","4_output_ports",),
    ("region_comb_3","version_simple","8_output_ports"),
    ("region_comb_3","4_output_ports",),
    ("region_comb_3","8_output_ports"),

    ("region_comb_4","version_register",),
    ("region_comb_4","version_register","4_output_ports",),
    ("region_comb_4","version_register","8_output_ports"),
    ("region_comb_4","version_simple",),
    ("region_comb_4","version_simple","4_output_ports",),
    ("region_comb_4","version_simple","8_output_ports"),
    ("region_comb_4","4_output_ports",),
    ("region_comb_4","8_output_ports"),

    ("region_comb_5","version_register",),
    ("region_comb_5","version_register","4_output_ports",),
    ("region_comb_5","version_register","8_output_ports"),
    ("region_comb_5","version_simple",),
    ("region_comb_5","version_simple","4_output_ports",),
    ("region_comb_5","version_simple","8_output_ports"),
    ("region_comb_5","4_output_ports",),
    ("region_comb_5","8_output_ports"),

    ("region_comb_6","version_register",),
    ("region_comb_6","version_register","4_output_ports",),
    ("region_comb_6","version_register","8_output_ports"),
    ("region_comb_6","version_simple",),
    ("region_comb_6","version_simple","4_output_ports",),
    ("region_comb_6","version_simple","8_output_ports"),
    ("region_comb_6","4_output_ports",),
    ("region_comb_6","8_output_ports"),

    ("pcie","version_register",),
    ("pcie","version_register","4_output_ports",),
    ("pcie","version_register","8_output_ports"),
    ("pcie","version_simple",),
    ("pcie","version_simple","4_output_ports",),
    ("pcie","version_simple","8_output_ports"),
    ("pcie","4_output_ports",),
    ("pcie","8_output_ports"),

    ("medium_frames",),
    ("small_frames",),
    ),
}
