# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

#             CMP_SYNTH # encapsulation of GEN_CMP with registers
TOP_LEVEL_ENT=GEN_CMP

SYNTH=vivado
#export CLK_PERIOD=4.0
#export DEVICE=AGILEX

all: comp
include ../../../../../build/Makefile
.PHONY: all
