# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ASFIFO_DMA_BUS

CLK_PORTS=WR_CLK RD_CLK
CLK_PERIOD=3 7.7

.PHONY: all
all: comp

include ../../../../../build/Makefile
