# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ASFIFO_BRAM

CLK_PORTS=CLK_WR CLK_RD
CLK_PERIOD=5.00 3.20

.PHONY: all
all: comp

include ../../../../../build/Makefile
