# Makefile: Makefile to compile module
# Copyright (C) 2025 CESNET z. s. p. o.
# Author(s): Ondrej Schwarz <ondrejschwarz@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=RX_MAC_LITE_ADAPTER_MAC_SEG
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../../../../build/Makefile
