# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

#             COUNT_TOP # encapsulation of COUNT_DSP with registers
TOP_LEVEL_ENT=COUNT_DSP

SYNTH=vivado
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

all: comp
include ../../../../../build/Makefile
.PHONY: all
