# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET
# Author: Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MVB_LOOKUP_TABLE
SYNTH=quartus

all: comp
include ../../../../../build/Makefile
.PHONY: all
