# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=EXTRACT_4B_SYNT
TOP_LEVEL_ARCHGRP=SYNTH

.PHONY: all
all: comp

include ../../../../../build/Makefile
