// extension_sequences.sv: Generate extension transactions for the RX MVB
// Copyright (C) 2025 CESNET z. s. p. o.
// Author(s): Yaroslav Marushchenko <xmarus09@stud.fit.vutbr.cz>
// SPDX-License-Identifier: BSD-3-Clause

virtual class extension_sequence_base #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends uvm_logic_vector::sequence_simple #(RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_base)

    localparam int unsigned MAX_DATA_LENGTH = PKT_MTU;
    localparam int unsigned MIN_DATA_LENGTH = 64;

    localparam int unsigned MAX_EXTENSION_ONLY_LENGTH = MAX_DATA_LENGTH - (MAX_DATA_LENGTH % MFB_BLOCK_SIZE); // The closest value divisible by MFB_BLOCK_SIZE and less than or equal to MAX_DATA_LENGTH
    localparam int unsigned MAX_EXTENSION_LENGTH      = (MAX_DATA_LENGTH-MIN_DATA_LENGTH) - ((MAX_DATA_LENGTH-MIN_DATA_LENGTH) % MFB_BLOCK_SIZE); // The closest value divisible by MFB_BLOCK_SIZE and less than or equal to (MAX_DATA_LENGTH-MIN_DATA_LENGTH)
    localparam int unsigned MIN_EXTENSION_LENGTH      = 60 - (60 % MFB_BLOCK_SIZE) + MFB_BLOCK_SIZE; // The closest value divisible by MFB_BLOCK_SIZE and greater than or equal to 60

    rand int unsigned transaction_count;

    // Stores the lengths of data frames generated by an RX MFB sequence
    mailbox #(int unsigned) frame_lengths;

    // Constructor
    function new(string name = "extension_sequence_base");
        super.new(name);
    endfunction

    // Gets a `frame_lengths` mailbox reference from the database
    function void load_from_db();
        assert(uvm_config_db #(mailbox #(int unsigned))::get(m_sequencer, "", "frame_lengths", frame_lengths))
        else begin
            `uvm_fatal(m_sequencer.get_full_name(), "\n\tCannot get the mailbox")
        end
    endfunction

    pure virtual task body;

endclass

// ------------------- //
// Extending sequences //
// ------------------- //

class extension_sequence #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 30;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        load_from_db();

        repeat (transaction_count) begin
            int unsigned frame_length;

            frame_lengths.get(frame_length);

            if (frame_length+MIN_EXTENSION_LENGTH > PKT_MTU) begin
                `uvm_do_with(req, {
                    req.data[1-1 -: 1] == 0; // RX_MVB_EXT_EN
                    // RX_MVB_FRAME_LENGTH
                    req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
                })
            end
            else begin
                `uvm_do_with(req, {
                    req.data[1-1   -: 1] == 1; // RX_MVB_EXT_EN
                    req.data[1+1-1 -: 1] == 0; // RX_MVB_EXT_ONLY
                    // RX_MVB_EXT_SIZE
                    (req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] % MFB_BLOCK_SIZE) == 0;     // (RX_MVB_EXT_SIZE % MFB_BLOCK_SIZE) = 0
                    req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] >= MIN_EXTENSION_LENGTH;     // RX_MVB_EXT_SIZE >= MIN_EXTENSION_LENGTH
                    req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] <= MAX_EXTENSION_LENGTH;     // RX_MVB_EXT_SIZE <= MAX_EXTENSION_LENGTH
                    (req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] + frame_length) <= PKT_MTU; // RX_MVB_EXT_SIZE+frame_length <= PKT_MTU
                    // RX_MVB_FRAME_LENGTH
                    req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
                })
            end
        end
    endtask

endclass

class extension_sequence_min #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_min #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_min)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 30;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence_min");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        load_from_db();

        repeat (transaction_count) begin
            int unsigned frame_length;

            frame_lengths.get(frame_length);

            if (frame_length+MIN_EXTENSION_LENGTH > PKT_MTU) begin
                `uvm_do_with(req, {
                    req.data[1-1 -: 1] == 0; // RX_MVB_EXT_EN
                    // RX_MVB_FRAME_LENGTH
                    req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
                })
            end
            else begin
                `uvm_do_with(req, {
                    req.data[1-1   -: 1] == 1; // RX_MVB_EXT_EN
                    req.data[1+1-1 -: 1] == 0; // RX_MVB_EXT_ONLY
                    // RX_MVB_EXT_SIZE
                    req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == MIN_EXTENSION_LENGTH; // RX_MVB_EXT_SIZE = MIN_EXTENSION_LENGTH
                    // RX_MVB_FRAME_LENGTH
                    req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
                })
            end
        end
    endtask

endclass

class extension_sequence_max #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_max #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_max)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 30;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence_max");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        load_from_db();

        repeat (transaction_count) begin
            int unsigned frame_length;

            frame_lengths.get(frame_length);

            if (frame_length+MAX_EXTENSION_LENGTH > PKT_MTU) begin
                `uvm_do_with(req, {
                    req.data[1-1 -: 1] == 0; // RX_MVB_EXT_EN
                    // RX_MVB_FRAME_LENGTH
                    req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
                })
            end
            else begin
                `uvm_do_with(req, {
                    req.data[1-1   -: 1] == 1; // RX_MVB_EXT_EN
                    req.data[1+1-1 -: 1] == 0; // RX_MVB_EXT_ONLY
                    // RX_MVB_EXT_SIZE
                    req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == MAX_EXTENSION_LENGTH; // RX_MVB_EXT_SIZE = MAX_EXTENSION_LENGTH
                    // RX_MVB_FRAME_LENGTH
                    req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
                })
            end
        end
    endtask

endclass

class extension_sequence_off #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_off #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_off)

    int unsigned transaction_count_min = 1;
    int unsigned transaction_count_max = 5;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence_off");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        load_from_db();

        repeat (transaction_count) begin
            int unsigned frame_length;

            frame_lengths.get(frame_length);

            `uvm_do_with(req, {
                req.data[1-1 -: 1] == 0; // RX_MVB_EXT_EN
                // RX_MVB_FRAME_LENGTH
                req.data[$clog2(PKT_MTU+1)+$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == frame_length;
            })
        end
    endtask

endclass

// -------------------- //
// Generating sequences //
// -------------------- //

class extension_sequence_only #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_only #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_only)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 30;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence_only");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        repeat (transaction_count) begin
            `uvm_do_with(req, {
                req.data[1-1   -: 1] == 1; // RX_MVB_EXT_EN
                req.data[1+1-1 -: 1] == 1; // RX_MVB_EXT_ONLY
                // RX_MVB_EXT_SIZE
                (req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] % MFB_BLOCK_SIZE) == 0; // (RX_MVB_EXT_SIZE % MFB_BLOCK_SIZE) = 0
                req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] >= MIN_EXTENSION_LENGTH; // RX_MVB_EXT_SIZE >= MIN_EXTENSION_LENGTH
                req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] <= MAX_DATA_LENGTH;      // RX_MVB_EXT_SIZE <= MAX_DATA_LENGTH
            })
        end
    endtask

endclass

class extension_sequence_only_min #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_only_min #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_only_min)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 30;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence_only_min");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        repeat (transaction_count) begin
            `uvm_do_with(req, {
                req.data[1-1   -: 1] == 1; // RX_MVB_EXT_EN
                req.data[1+1-1 -: 1] == 1; // RX_MVB_EXT_ONLY
                // RX_MVB_EXT_SIZE
                req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == MIN_EXTENSION_LENGTH; // RX_MVB_EXT_SIZE = MIN_EXTENSION_LENGTH
            })
        end
    endtask

endclass

class extension_sequence_only_max #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends extension_sequence_base #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH);
    `uvm_object_param_utils(test::extension_sequence_only_max #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `m_uvm_get_type_name_func(test::extension_sequence_only_max)

    int unsigned transaction_count_min = 15;
    int unsigned transaction_count_max = 30;

    constraint c_transaction_count { transaction_count inside { [transaction_count_min : transaction_count_max] }; }

    // Constructor
    function new(string name = "extension_sequence_only_max");
        super.new(name);
    endfunction

    // Generates transactions
    task body;
        repeat (transaction_count) begin
            `uvm_do_with(req, {
                req.data[1-1   -: 1] == 1; // RX_MVB_EXT_EN
                req.data[1+1-1 -: 1] == 1; // RX_MVB_EXT_ONLY
                // RX_MVB_EXT_SIZE
                req.data[$clog2(PKT_MTU+1)+1+1-1 -: $clog2(PKT_MTU+1)] == MAX_EXTENSION_ONLY_LENGTH; // RX_MVB_EXT_SIZE = MAX_EXTENSION_ONLY_LENGTH
            })
        end
    endtask

endclass

// ---------------- //
// Sequence library //
// ---------------- //

class extension_sequence_library #(int unsigned MFB_BLOCK_SIZE, int unsigned PKT_MTU, int unsigned RX_MVB_ITEM_WIDTH) extends uvm_common::sequence_library #(uvm_logic_vector::config_sequence, uvm_logic_vector::sequence_item #(RX_MVB_ITEM_WIDTH));
    `uvm_object_param_utils(test::extension_sequence_library #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))
    `uvm_sequence_library_utils(test::extension_sequence_library #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH))

    function new(string name = "extension_sequence_library");
        super.new(name);

        init_sequence_library();
    endfunction

    function void init_sequence(uvm_logic_vector::config_sequence param_cfg = null);
        super.init_sequence(param_cfg);

        add_sequence(extension_sequence          #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
        add_sequence(extension_sequence_min      #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
        add_sequence(extension_sequence_max      #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
        add_sequence(extension_sequence_off      #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
        add_sequence(extension_sequence_only     #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
        add_sequence(extension_sequence_only_min #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
        add_sequence(extension_sequence_only_max #(MFB_BLOCK_SIZE, PKT_MTU, RX_MVB_ITEM_WIDTH)::get_type());
    endfunction

endclass
