# Makefile: Makefile script to compile specified module
# Copyright (C) 2020 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DSP_COUNTER_INTEL

SYNTH=quartus
#export CLK_PERIOD=4.0
export DEVICE=AGILEX #STRATIX10

all: comp
include ../../../../../build/Makefile
.PHONY: all
