-- SPDX-License-Identifier: BSD-3-Clause
-- Copyright (C) 2026 CESNET z. s. p. o
-- Author(s): Ondrej Schwarz <ondrejschwarz@cesnet.cz>

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.math_pack.all;
use work.type_pack.all;

-- Random diffusion component of the PCASD algorithm,
-- combining the key extension and mixing rounds,
-- downscalled to 32-bits.
--
-- The algorithm with 256-bit block is defined as follows
-- (operations are perfomed in parallel):
--  with:
--      Σ0(x) = x ^ ROTL13(x) ^ ROTL14(x)
--
--      Σ1(x) = x ^ ROTL31(x) ^ ROTL29(x)
--
--      Ch(x, y, z)  = (x & y) ^ (~x & z)
--
--      Maj(x, y, z) = (x & y) ^ (x & z) ^ (y & z)
--
--      CA(state, rule, 1) => one round of the celluar automaton
--
--      MW => key split into 32-bit words
--
--      k => index of the round, 0 <= k <= RD_ROUNDS
--
--  MW_LAST = {
--      k in <BLOCK_WORDS, SIGMA1_FIRST):
--          Σ0(MW[0] ^ ROTL7(MW[7]) ^ ROTL1(MW[3])) ^ ROTL19(MW[5])
--      k in <SIGMA1_FIRST, RD_ROUNDS * 2 + 4):
--          Σ1(MW[0] ^ ROTL7(MW[7]) ^ ROTL1(MW[3])) ^ ROTL19(MW[5])
--  };
--
--  MW_A = MW[0] ^ MW[4];
--
--  A = Maj(A, B, C) + D + ROTL7(ROTL12(A) + E + ROTLk(K[k])) + ROTL12(A) + MW_A;
--  B = CA(A, rules[k % 16], 1);
--  C = ROTL9(B);
--  D = C;
--  E = Σ0(Ch(A, B, C) + H + ROTL7(ROTL12(A) + E + ROTLk(K[k])) + MW[0]);
--  F = E;
--  G = ROTL19(F);
--  H = G;
--
-- Only a slice of the extended key needed in the round
-- and to calculate the next word of the key is passed
-- as IN_KEY. The word of the key used in this round
-- is then shifted out of the key when the key is returned
-- via the OUT_KEY port
entity PCASD_RD_ROUND is
    generic (
        -- width of the slice of the extended key processed
        -- in this round.
        KEY_WIDTH   : natural   := 288;
        -- width of the block
        BLOCK_WIDTH : natural   := 256;
        -- width of the passthrough metadata
        META_WIDTH  : natural   := 32;
        -- number of random diffusion rounds per block
        RD_ROUNDS   : natural   := 8;
        -- index of this round
        ROUND_INDEX : natural   := 0;
        -- chosen chaotic rules of the celluar automaton
        CA_RULES    : n_array_t := (90, 105, 60, 75, 135, 165, 149, 45, 89, 150, 30, 101, 102, 153, 86, 195);
        -- setup of the registers of this component
        REG_SETUP   : std_logic_vector(6-1 downto 0) := "111111"
    );
    port (
        -- main clock
        CLK         : in  std_logic;
        -- synchronious reset
        RESET       : in  std_logic;
        -- extended key slice input
        IN_KEY      : in  unsigned(KEY_WIDTH-1 downto 0);
        -- internal state variables input
        IN_A        : in  unsigned(32-1 downto 0);
        IN_B        : in  unsigned(32-1 downto 0);
        IN_C        : in  unsigned(32-1 downto 0);
        IN_D        : in  unsigned(32-1 downto 0);
        IN_E        : in  unsigned(32-1 downto 0);
        IN_F        : in  unsigned(32-1 downto 0);
        IN_G        : in  unsigned(32-1 downto 0);
        IN_H        : in  unsigned(32-1 downto 0);
        -- seed passthrough input
        IN_SEED     : in  unsigned(128-1 downto 0);
        -- metadata input
        IN_META     : in  std_logic_vector(META_WIDTH-1 downto 0);
        -- validity of input
        IN_VALID    : in  std_logic;

        -- shifted extended key slice output
        OUT_KEY     : out unsigned(KEY_WIDTH-1 downto 0);
        -- internal state variables output
        OUT_A       : out unsigned(32-1 downto 0);
        OUT_B       : out unsigned(32-1 downto 0);
        OUT_C       : out unsigned(32-1 downto 0);
        OUT_D       : out unsigned(32-1 downto 0);
        OUT_E       : out unsigned(32-1 downto 0);
        OUT_F       : out unsigned(32-1 downto 0);
        OUT_G       : out unsigned(32-1 downto 0);
        OUT_H       : out unsigned(32-1 downto 0);
        -- seed passthrough output
        OUT_SEED    : out unsigned(128-1 downto 0);
        -- metadata output
        OUT_META    : out std_logic_vector(META_WIDTH-1 downto 0);
        -- valid passthrough
        OUT_VALID   : out std_logic
    );
end entity;

architecture FULL of PCASD_RD_ROUND is
    -- indexes of the words chosen in the key extension process change
    -- based on the width of the block
    function f_get_word_choice (block_width: natural) return n_array_t is
        variable res : n_array_t(0 to 4-1);
    begin
        case block_width is
            when 128 => res := (4, 1, 3, 2);
            when 256 => res := (8, 1, 5, 3);
            when others => null;
        end case;

        return res;
    end function;

    -- 64 contant variables Kk generated by taking the first 64-bits
    -- of SHA256(k), k = 1,2, ..., 64
    constant K : u_array_t(0 to 63)(64-1 downto 0) := (
        X"6B86B273FF34FCE1", X"D4735E3A265E16EE", X"4E07408562BEDB8B", X"4B227777D4DD1FC6",
        X"EF2D127DE37B942B", X"E7F6C011776E8DB7", X"7902699BE42C8A8E", X"2C624232CDD22177",
        X"19581E27DE7CED00", X"4A44DC15364204A8", X"4FC82B26AECB47D2", X"6B51D431DF5D7F14",
        X"3FDBA35F04DC8C46", X"8527A891E2241369", X"E629FA6598D73276", X"B17EF6D19C7A5B1E",
        X"4523540F1504CD17", X"4EC9599FC203D176", X"9400F1B21CB527D7", X"F5CA38F748A1D6EA",
        X"6F4B6612125FB3A0", X"785F3EC7EB32F30B", X"535FA30D7E25DD8A", X"C2356069E9D1E79C",
        X"B7A56873CD771F2C", X"5F9C4AB08CAC7457", X"670671CD97404156", X"59E19706D51D39F6",
        X"35135AAA6CC23891", X"624B60C58C9D8BFB", X"EB1E33E8A81B697B", X"E29C9C180C6279B0",
        X"C6F3AC57944A5314", X"86E5014965866131", X"9F14025AF0065B30", X"76A50887D8F1C2E9",
        X"7A61B53701BEFDAE", X"AEA92132C4CBEB26", X"0B918943DF0962BC", X"D59ECED1DED07F84",
        X"3D914F9348C9CC0F", X"73475CB40A568E8D", X"44CB730C420480A0", X"71EE45A3C0DB9A98",
        X"811786AD1AE74ADF", X"25FC0E7096FC6537", X"31489056E0916D59", X"98010BD9270F9B10",
        X"0E17DACA5F3E175F", X"1A6562590EF19D10", X"031B4AF5197EC30A", X"41CFC0D1F2D127B0",
        X"2858DCD1057D3EAE", X"2FCA346DB6561871", X"02D20BBD7E394AD5", X"7688B6EF52555962",
        X"C837649CCE43F272", X"6208EF0F7750C111", X"3E1E967E9B793E90", X"39FA9EC190EEE7B6",
        X"D029FA3A95E174A1", X"81B8A03F97E8787C", X"DA4EA2A5506F2693", X"A68B412C4282555F"
    );

    -- constant variable Kk chosen and rotated base on the index of this round
    constant ROTLK_KK       : unsigned(32-1 downto 0) := rotate_left(K(ROUND_INDEX)(32-1 downto 0), ROUND_INDEX);
    -- number of words per block
    constant BLOCK_WORDS    : natural := BLOCK_WIDTH / 32;
    -- last extension word created by sigma0 before switching to sigma1
    constant SIGMA1_FIRST   : natural := (RD_ROUNDS + 4) / 2;
    -- index of the last word of the extended key slice in the context of the
    -- whole entended key
    constant MW_LAST_INDEX  : natural := ROUND_INDEX + BLOCK_WORDS;
    -- Message Word Choice - indexes of the message words selected in the
    -- key extension process
    constant MWC            : n_array_t(0 to 4-1)    := f_get_word_choice(BLOCK_WIDTH);
    -- celluar automaton rule chosen in for this round
    constant CA_RULE        : unsigned(8-1 downto 0) := to_unsigned(CA_RULES(ROUND_INDEX mod 16), 8);
    -- length of the pipeline of this component
    constant PIPE_LENGTH    : natural := 6;

    -- logic
    -- extended key
    signal key   : u_array_2d_t(PIPE_LENGTH-1 downto 0)(BLOCK_WORDS downto 0)(32-1 downto 0);
    -- state variables
    signal a     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal b     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal c     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal d     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal e     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal f     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal g     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal h     : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    -- temporary variables
    signal t0    : u_array_t(PIPE_LENGTH-1 downto 2)(32-1 downto 0);
    signal t1    : u_array_t(PIPE_LENGTH-1 downto 2)(32-1 downto 0);
    signal t2    : u_array_t(PIPE_LENGTH-1 downto 3)(32-1 downto 0);
    signal t3    : u_array_t(PIPE_LENGTH-1 downto 3)(32-1 downto 0);
    signal t4    : unsigned(32-1 downto 0);
    signal t5    : unsigned(32-1 downto 0);

    -- shifted extended key, removing unnecesary word on the
    -- index 0 and freeing up space for new extension word.
    signal key_out : unsigned(KEY_WIDTH-1 downto 0);

    -- registers
    -- extended key register
    signal key_reg : u_array_2d_t(PIPE_LENGTH-1 downto 0)(BLOCK_WORDS downto 0)(32-1 downto 0);
    -- state registers
    signal a_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal b_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal c_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal d_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal e_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal f_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal g_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    signal h_reg   : u_array_t(PIPE_LENGTH-1 downto 0)(32-1 downto 0);
    -- temporary registers
    signal t0_reg  : u_array_t(PIPE_LENGTH-2 downto 1)(32-1 downto 0);
    signal t1_reg  : u_array_t(PIPE_LENGTH-2 downto 1)(32-1 downto 0);
    signal t2_reg  : u_array_t(PIPE_LENGTH-2 downto 2)(32-1 downto 0);
    signal t3_reg  : u_array_t(PIPE_LENGTH-2 downto 2)(32-1 downto 0);
    signal t4_reg  : unsigned(32-1 downto 0);
    signal t5_reg  : unsigned(32-1 downto 0);

    -- passthrough signal registers
    signal seed    : u_array_t(PIPE_LENGTH-1 downto 0)(128-1 downto 0);
    signal vld     : std_logic_vector(PIPE_LENGTH-1 downto 0);
    signal meta    : slv_array_t(PIPE_LENGTH-1 downto 0)(META_WIDTH-1 downto 0);

begin
    -- ================================================
    --                      INPUT
    -- ================================================
    -- spliting the key up into words
    key_reg(5) <= slv_arr_to_u_arr(slv_array_downto_deser(std_logic_vector(IN_KEY), BLOCK_WORDS + 1));

    a_reg(5)   <= IN_A;
    b_reg(5)   <= IN_B;
    c_reg(5)   <= IN_C;
    d_reg(5)   <= IN_D;
    e_reg(5)   <= IN_E;
    f_reg(5)   <= IN_F;
    g_reg(5)   <= IN_G;
    h_reg(5)   <= IN_H;
    vld(5)     <= IN_VALID;
    seed(5)    <= IN_SEED;
    meta(5)    <= IN_META;

    -- ================================================
    --                     LOGIC
    -- ================================================

    -- STEP 1:

    -- A {
    -- Maj(A, B, C) - (x & y) in t0
    t0(5) <= a_reg(5) and b_reg(5);
    --  Maj(A, B, C) - (x & z) in t1
    t1(5) <= a_reg(5) and c_reg(5);
    --  Maj(A, B, C) - (y & z) in t2
    t2(5) <= b_reg(5) and c_reg(5);
    -- ROTL12(A) in t3
    t3(5) <= rotate_left(a_reg(5), 12);
    -- E + ROTLk(Kk) in t4
    t4    <= e_reg(5) + ROTLK_KK;
    -- }

    -- E {
    -- Ch(A, B, C) - ~x in t5
    t5    <= not a_reg(5);
    -- }

    -- key extension
    key(5)(BLOCK_WORDS) <= key_reg(5)(BLOCK_WORDS - MWC(0)) xor rotate_left(key_reg(5)(BLOCK_WORDS - MWC(1)), 7) xor rotate_left(key_reg(5)(BLOCK_WORDS - MWC(2)), 1);

    -- not updated
    a(5) <= a_reg(5);
    b(5) <= b_reg(5);
    c(5) <= c_reg(5);
    d(5) <= d_reg(5);
    e(5) <= e_reg(5);
    f(5) <= f_reg(5);
    g(5) <= g_reg(5);
    h(5) <= h_reg(5);

    -- updating the rest of the key
    key(5)(BLOCK_WORDS-1 downto 0) <= key_reg(5)(BLOCK_WORDS-1 downto 0);

    -- STEP 2:

    -- A {
    -- Maj(A, B, C) in a
    a(4)  <= t0_reg(4) xor t1_reg(4) xor t2_reg(4);
    -- ROTL12(A) + D in t0
    t0(4) <= t3_reg(4) + d_reg(4);
    -- ROTL7(ROTL12(A) + E + ROTLk(Kk)) in t1
    t1(4) <= rotate_left(t3_reg(4) + t4_reg, 7);
    -- }

    -- E {
    -- Ch(A, B, C) - (~x & z) in e => frees up C
    t2(4) <= t5_reg and c_reg(4);
    -- Ch(A, B, C) - (x & y) in t2
    t3(4) <= a_reg(4) and b_reg(4);
    -- }

    -- new B
    ca_round_i: entity work.PCASD_CA_ROUND
    generic map (
        STATE_WIDTH => 32,
        META_WIDTH  => META_WIDTH,
        OUT_REG     => false
    ) port map (
        CLK        => CLK,
        RESET      => RESET,
        IN_STATE   => a_reg(4),
        IN_RULE    => CA_RULE,
        IN_SEED    => (others => '0'),
        IN_META    => (others => '0'),
        IN_VALID   => '0',
        OUT_STATE  => b(4),
        OUT_RULE   => open,
        OUT_SEED   => open,
        OUT_META   => open,
        OUT_VALID  => open
    );

    -- new C
    c(4) <= rotate_left(b_reg(4), 9);

    -- new D
    d(4) <= c_reg(4);

    -- key extension
    sigma_ext_g: if MW_LAST_INDEX < SIGMA1_FIRST generate
        key(4)(BLOCK_WORDS) <= key_reg(4)(BLOCK_WORDS) xor rotate_left(key_reg(4)(BLOCK_WORDS), 13) xor rotate_left(key_reg(4)(BLOCK_WORDS), 14);
    else generate
        key(4)(BLOCK_WORDS) <= key_reg(4)(BLOCK_WORDS) xor rotate_left(key_reg(4)(BLOCK_WORDS), 31) xor rotate_left(key_reg(4)(BLOCK_WORDS), 29);
    end generate;

    -- not updated
    e(4) <= e_reg(4);
    f(4) <= f_reg(4);
    g(4) <= g_reg(4);
    h(4) <= h_reg(4);

    -- updating the rest of the key
    key(4)(BLOCK_WORDS-1 downto 0) <= key_reg(4)(BLOCK_WORDS-1 downto 0);

    -- STEP 3:
    -- Maj(A, B, C) in a

    -- A {
    -- ROTL12(A) + D + ROTL7(ROTL12(A) + E + ROTLk(Kk)) in t0
    t0(3) <= t0_reg(3) + t1_reg(3);
    -- }

    -- E {
    -- Ch(A, B, C) in e
    e(3)  <= t2_reg(3) xor t3_reg(3);
    -- H + ROTL7(ROTL12(A) + E + ROTLk(Kk)) in t1
    t1(3) <= h_reg(3) + t1_reg(3); --+ t3_reg(2);
    -- }

    -- new F
    f(3) <= e_reg(3);

    -- new G
    g(3) <= rotate_left(f_reg(3), 19);

    -- new H
    h(3) <= g_reg(3);

    -- key extension - MW_E
    key(3)(BLOCK_WORDS) <= key_reg(3)(BLOCK_WORDS) xor rotate_left(key_reg(3)(BLOCK_WORDS - MWC(3)), 19);

    -- not updated
    a(3) <= a_reg(3);
    b(3) <= b_reg(3);
    c(3) <= c_reg(3);
    d(3) <= d_reg(3);

    -- updating the rest of the key
    key(3)(BLOCK_WORDS-1 downto 0) <= key_reg(3)(BLOCK_WORDS-1 downto 0);

    -- STEP 4:
    -- A {
    -- Maj(A, B, C) + D + ROTL7(ROTL12(A) + E + ROTLk(Kk)) in a
    a(2) <= a_reg(2) + t0_reg(2);
    -- }

    -- E {
    -- Ch(A, B, C) + H + ROTL7(ROTL12(A) + E + ROTLk(Kk)) in e
    e(2) <= e_reg(2) + t1_reg(2);
    -- }

    -- key extension - MW[k + RD_ROUNDS + 4]
    t0(2) <= key_reg(2)(0) xor key_reg(2)(4);

    -- not updated
    b(2)   <= b_reg(2);
    c(2)   <= c_reg(2);
    d(2)   <= d_reg(2);
    f(2)   <= f_reg(2);
    g(2)   <= g_reg(2);
    h(2)   <= h_reg(2);
    key(2) <= key_reg(2);

    -- STEP 5:
    -- new A
    a(1) <= a_reg(1) + t0_reg(1);

    -- Ch(A, B, C) + H + ROTL7(ROTL12(A) + E + ROTLk(Kk)) + MW[k] in e
    e(1) <= e_reg(1) + key_reg(1)(0);

    -- not updated
    b(1)   <= b_reg(1);
    c(1)   <= c_reg(1);
    d(1)   <= d_reg(1);
    f(1)   <= f_reg(1);
    g(1)   <= g_reg(1);
    h(1)   <= h_reg(1);
    key(1) <= key_reg(1);

    -- STEP 6:
    -- new E
    e(0) <= e_reg(0) xor rotate_left(e_reg(0), 13) xor rotate_left(e_reg(0), 14);

    -- not updated
    a(0)   <= a_reg(0);
    b(0)   <= b_reg(0);
    c(0)   <= c_reg(0);
    d(0)   <= d_reg(0);
    f(0)   <= f_reg(0);
    g(0)   <= g_reg(0);
    h(0)   <= h_reg(0);
    key(0) <= key_reg(0);

    -- signal for outputing a shifted key
    key_out <= shift_right(unsigned(slv_array_ser(u_arr_to_slv_arr(key(0)))), 32);

    -- ================================================
    --                    PIPELINE
    -- ================================================
    pipeline_g: for i in PIPE_LENGTH-1 downto 1 generate

        reg_g: if REG_SETUP(i) = '1' generate

            -- register updating signals that exist at every point of the pipeline
            process (CLK)
            begin
                if rising_edge(CLK) then
                    key_reg(i-1) <= key(i);
                    a_reg(i-1)   <= a(i);
                    b_reg(i-1)   <= b(i);
                    c_reg(i-1)   <= c(i);
                    d_reg(i-1)   <= d(i);
                    e_reg(i-1)   <= e(i);
                    f_reg(i-1)   <= f(i);
                    g_reg(i-1)   <= g(i);
                    h_reg(i-1)   <= h(i);
                    seed(i-1)    <= seed(i);
                    meta(i-1)    <= meta(i);
                    vld(i-1)     <= vld(i);

                    if (RESET = '1') then
                        vld(i-1) <= '0';
                    end if;
                end if;
            end process;

            -- registers updating temporary signals
            t0_t1_reg_g : if (i <= PIPE_LENGTH-1 and i > 1) generate
                process (CLK)
                begin
                    if rising_edge(CLK) then
                        t0_reg(i-1) <= t0(i);
                        t1_reg(i-1) <= t1(i);
                    end if;
                end process;
            end generate;

            t2_t3_reg_g: if (i <= PIPE_LENGTH-1 and i > 2) generate
                process (CLK)
                begin
                    if rising_edge(CLK) then
                        t2_reg(i-1) <= t2(i);
                        t3_reg(i-1) <= t3(i);
                    end if;
                end process;
            end generate;

            t4_t5_reg_g: if (i = PIPE_LENGTH-1) generate
                process (CLK)
                begin
                    if rising_edge(CLK) then
                        t4_reg <= t4;
                        t5_reg <= t5;
                    end if;
                end process;
            end generate;

        else generate
            -- connecting signals that exist at every point of the pipeline
            key_reg(i-1) <= key(i);
            a_reg(i-1)   <= a(i);
            b_reg(i-1)   <= b(i);
            c_reg(i-1)   <= c(i);
            d_reg(i-1)   <= d(i);
            e_reg(i-1)   <= e(i);
            f_reg(i-1)   <= f(i);
            g_reg(i-1)   <= g(i);
            h_reg(i-1)   <= h(i);
            seed(i-1)    <= seed(i);
            meta(i-1)    <= meta(i);
            vld(i-1)     <= vld(i);

            -- connecting temporary signals
            t0_t1_conn_g : if (i <= PIPE_LENGTH-1 and i > 1) generate
                t0_reg(i-1) <= t0(i);
                t1_reg(i-1) <= t1(i);
            end generate;

            t2_t3_conn_g: if (i <= PIPE_LENGTH-1 and i > 2) generate
                t2_reg(i-1) <= t2(i);
                t3_reg(i-1) <= t3(i);
            end generate;

            t4_t5_conn_g: if (i = PIPE_LENGTH-1) generate
                t4_reg <= t4;
                t5_reg <= t5;
            end generate;

        end generate;

    end generate;

    -- ================================================
    --                     OUTPUT
    -- ================================================
    out_reg_g: if REG_SETUP(0) = '1' generate

        process (CLK)
        begin
            if rising_edge(CLK) then
                OUT_KEY   <= key_out;
                OUT_A     <= a(0);
                OUT_B     <= b(0);
                OUT_C     <= c(0);
                OUT_D     <= d(0);
                OUT_E     <= e(0);
                OUT_F     <= f(0);
                OUT_G     <= g(0);
                OUT_H     <= h(0);
                OUT_SEED  <= seed(0);
                OUT_META  <= meta(0);
                OUT_VALID <= vld(0);

                if (RESET = '1') then
                    OUT_VALID <= '0';
                end if;
            end if;
        end process;

    else generate
        OUT_KEY   <= key_out;
        OUT_A     <= a(0);
        OUT_B     <= b(0);
        OUT_C     <= c(0);
        OUT_D     <= d(0);
        OUT_E     <= e(0);
        OUT_F     <= f(0);
        OUT_G     <= g(0);
        OUT_H     <= h(0);
        OUT_SEED  <= seed(0);
        OUT_META  <= meta(0);
        OUT_VALID <= vld(0);
    end generate;

end architecture;
