# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=NP_LUTRAM_PRO
#SYNTH=quartus
#DEVICE=AGILEX
CLK_PORTS=WCLK WCLKN
CLK_PERIOD=4 2

.PHONY: all
all: comp

include ../../../../../build/Makefile
