# Makefile: Common make script for firmware targets
# Copyright (C) 2022 CESNET
# Author: Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

MK_PATHS_BASE := $(dir $(lastword $(MAKEFILE_LIST)))
include $(MK_PATHS_BASE)ndk_paths.mk
include $(OFM_PATH)build/Makefile
