# Makefile: Makefile to compile specified module
# Copyright (C) 2020 CESNET
# Author: Martin Spinler <spinler@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DP_BRAM_XILINX

CLK_PORTS=CLKA CLKB

.PHONY: all
all: comp

include ../../../../../build/Makefile
