# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ASFIFO_MUX_1TO2

#SYNTH=quartus
#DEVICE=AGILEX
CLK_PORTS=CLK_WR CLK_WR
CLK_PERIOD=3 6.3

.PHONY: all
all: comp

include ../../../../../../build/Makefile
