# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=i2c_hw_mi32
TOP_LEVEL_PATH=../top

.PHONY: all
all: comp

include ../../../../build/Makefile
