# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DMA_MFB_GENERATOR
SYNTH=quartus

#DEVICE=ULTRASCALE
CLK_PORTS=CLK MI_CLK
#CLK_PERIOD=2.5

.PHONY: all
all: comp

include ../../../../../build/Makefile
