# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Daniel Kondys <xkondy00@vutbr.cz>
#

TOP_LEVEL_ENT=NETWORK_MOD_LOGIC
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE
#export DEVICE=AGILEX

all: comp
include ../../../../../../../../ofm/build/Makefile
.PHONY: all
