# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ASYNC_BUS_HANDSHAKE

CLK_PORTS=ACLK BCLK
CLK_PERIOD=5.00 4.00

.PHONY: all
all: comp

include ../../../../../build/Makefile
