# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ASFIFO_BRAM_XILINX

CLK_PORTS=CLK_WR CLK_RD
CLK_PERIOD=5 4

.PHONY: all
all: comp

include ../../../../../build/Makefile
