# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal   <cabal@cesnet.cz>
#            Daniel Kondys <xkondy00@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ETH_AVST_ADAPTER


SYNTH=quartus

CLK_PERIOD=2.480

.PHONY: all
all: comp

include ../../../../../../../../build/Makefile
