# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=RX_MAC_LITE_UMII
SYNTH=quartus

CLK_PORTS=MI_CLK RX_CLK TX_CLK
CLK_PERIOD=5 3 5

all: comp
include ../../../../../../../build/Makefile
.PHONY: all
