# Makefile: Makefile to synthesize DRAM_FIFO
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Adam Zatloukal <zatloukal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DRAM_FIFO
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

.PHONY: all
all: comp

include ../../../../../build/Makefile
