# pcie.xdc:
# Copyright (C) 2025 DynaNIC Semiconductors s.r.o.
# Author(s): Jan Privara <privara@dyna-nic.com>
#
# SPDX-License-Identifier: BSD-3-Clause

set_property PACKAGE_PIN AA4     [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN AA3     [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN AB2     [get_ports {PCIE_RX_P[1]}]
set_property PACKAGE_PIN AB1     [get_ports {PCIE_RX_N[1]}]
set_property PACKAGE_PIN AC4     [get_ports {PCIE_RX_P[2]}]
set_property PACKAGE_PIN AC3     [get_ports {PCIE_RX_N[2]}]
set_property PACKAGE_PIN AD2     [get_ports {PCIE_RX_P[3]}]
set_property PACKAGE_PIN AD1     [get_ports {PCIE_RX_N[3]}]
set_property PACKAGE_PIN AE4     [get_ports {PCIE_RX_P[4]}]
set_property PACKAGE_PIN AE3     [get_ports {PCIE_RX_N[4]}]
set_property PACKAGE_PIN AF2     [get_ports {PCIE_RX_P[5]}]
set_property PACKAGE_PIN AF1     [get_ports {PCIE_RX_N[5]}]
set_property PACKAGE_PIN AG4     [get_ports {PCIE_RX_P[6]}]
set_property PACKAGE_PIN AG3     [get_ports {PCIE_RX_N[6]}]
set_property PACKAGE_PIN AH2     [get_ports {PCIE_RX_P[7]}]
set_property PACKAGE_PIN AH1     [get_ports {PCIE_RX_N[7]}]
set_property PACKAGE_PIN AJ4     [get_ports {PCIE_RX_P[8]}]
set_property PACKAGE_PIN AJ3     [get_ports {PCIE_RX_N[8]}]
set_property PACKAGE_PIN AK2     [get_ports {PCIE_RX_P[9]}]
set_property PACKAGE_PIN AK1     [get_ports {PCIE_RX_N[9]}]
set_property PACKAGE_PIN AM2     [get_ports {PCIE_RX_P[10]}]
set_property PACKAGE_PIN AM1     [get_ports {PCIE_RX_N[10]}]
set_property PACKAGE_PIN AP2     [get_ports {PCIE_RX_P[11]}]
set_property PACKAGE_PIN AP1     [get_ports {PCIE_RX_N[11]}]
set_property PACKAGE_PIN AT2     [get_ports {PCIE_RX_P[12]}]
set_property PACKAGE_PIN AT1     [get_ports {PCIE_RX_N[12]}]
set_property PACKAGE_PIN AV2     [get_ports {PCIE_RX_P[13]}]
set_property PACKAGE_PIN AV1     [get_ports {PCIE_RX_N[13]}]
set_property PACKAGE_PIN AY2     [get_ports {PCIE_RX_P[14]}]
set_property PACKAGE_PIN AY1     [get_ports {PCIE_RX_N[14]}]
set_property PACKAGE_PIN BB2     [get_ports {PCIE_RX_P[15]}]
set_property PACKAGE_PIN BB1     [get_ports {PCIE_RX_N[15]}]

set_property PACKAGE_PIN Y7      [get_ports {PCIE_TX_P[0]}]
set_property PACKAGE_PIN Y6      [get_ports {PCIE_TX_N[0]}]
set_property PACKAGE_PIN AB7     [get_ports {PCIE_TX_P[1]}]
set_property PACKAGE_PIN AB6     [get_ports {PCIE_TX_N[1]}]
set_property PACKAGE_PIN AD7     [get_ports {PCIE_TX_P[2]}]
set_property PACKAGE_PIN AD6     [get_ports {PCIE_TX_N[2]}]
set_property PACKAGE_PIN AF7     [get_ports {PCIE_TX_P[3]}]
set_property PACKAGE_PIN AF6     [get_ports {PCIE_TX_N[3]}]
set_property PACKAGE_PIN AH7     [get_ports {PCIE_TX_P[4]}]
set_property PACKAGE_PIN AH6     [get_ports {PCIE_TX_N[4]}]
set_property PACKAGE_PIN AK7     [get_ports {PCIE_TX_P[5]}]
set_property PACKAGE_PIN AK6     [get_ports {PCIE_TX_N[5]}]
set_property PACKAGE_PIN AM7     [get_ports {PCIE_TX_P[6]}]
set_property PACKAGE_PIN AM6     [get_ports {PCIE_TX_N[6]}]
set_property PACKAGE_PIN AN5     [get_ports {PCIE_TX_P[7]}]
set_property PACKAGE_PIN AN4     [get_ports {PCIE_TX_N[7]}]
set_property PACKAGE_PIN AP7     [get_ports {PCIE_TX_P[8]}]
set_property PACKAGE_PIN AP6     [get_ports {PCIE_TX_N[8]}]
set_property PACKAGE_PIN AR5     [get_ports {PCIE_TX_P[9]}]
set_property PACKAGE_PIN AR4     [get_ports {PCIE_TX_N[9]}]
set_property PACKAGE_PIN AT7     [get_ports {PCIE_TX_P[10]}]
set_property PACKAGE_PIN AT6     [get_ports {PCIE_TX_N[10]}]
set_property PACKAGE_PIN AU5     [get_ports {PCIE_TX_P[11]}]
set_property PACKAGE_PIN AU4     [get_ports {PCIE_TX_N[11]}]
set_property PACKAGE_PIN AW5     [get_ports {PCIE_TX_P[12]}]
set_property PACKAGE_PIN AW4     [get_ports {PCIE_TX_N[12]}]
set_property PACKAGE_PIN BA5     [get_ports {PCIE_TX_P[13]}]
set_property PACKAGE_PIN BA4     [get_ports {PCIE_TX_N[13]}]
set_property PACKAGE_PIN BC5     [get_ports {PCIE_TX_P[14]}]
set_property PACKAGE_PIN BC4     [get_ports {PCIE_TX_N[14]}]
set_property PACKAGE_PIN BE5     [get_ports {PCIE_TX_P[15]}]
set_property PACKAGE_PIN BE4     [get_ports {PCIE_TX_N[15]}]

set_property PACKAGE_PIN AM17    [get_ports PCIE_SYSRST]
set_property PULLUP     true     [get_ports PCIE_SYSRST]
set_property IOSTANDARD LVCMOS12 [get_ports PCIE_SYSRST]

set_property PACKAGE_PIN AG9     [get_ports PCIE_SYSCLK_P]
set_property PACKAGE_PIN AG8     [get_ports PCIE_SYSCLK_N]

create_clock -period 10.000 -name pcie_clk [get_ports PCIE_SYSCLK_P]
