# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2025 CESNET
# Author(s): Ondrej Schwarz <ondrejschwarz@cesnet.cz>

TOP_LEVEL_ENT=HASH_WRAPPER
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
