# Makefile: Makefile script to compile specified module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s):Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=CROSSBARX
#SYNTH=quartus

#DEVICE=STRATIX10
CLK_PORTS=CLK CLK2 CLK_ARB
CLK_PERIOD=5 2.5 3.5

all: comp

include ../../../../../build/Makefile

.PHONY: all
