# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=ALU_DSP_TOP
TOP_LEVEL_ARCHGRP=SYNTH

.PHONY: all
all: comp

include ../../../../../build/Makefile
