# Makefile: Makefile to run the DRAM_FIFO cocotb test
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Adam Zatloukal <zatloukal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

# Test DRAM_FIFO component directly (AVMM ports are exposed for external memory)
TOP_LEVEL_ENT=DRAM_FIFO
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
