# Makefile: Makefile to compile module
# Copyright (C) 2025 DynaNIC Semiconductors, Ltd.
# Author(s): Jan Privara <privara@dyna-nic.com>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=mfb_discarder
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
