# Makefile: Makefile to compile module
# Copyright (C) 2026 Dynanic Semiconductors Ltd.
# Author(s): David Beneš <benes@dyna-nic.com>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MVB_SERIALIZER

SYNTH=quartus
export DEVICE=AGILEX

.PHONY: all
all: comp

include ../../../../../build/Makefile
