# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=FLU_PFIFO

CLK_PORTS=RX_CLK TX_CLK
CLK_PERIOD=5 6.4

.PHONY: all
all: comp

include ../../../../../build/Makefile
