# Makefile: Makefile script to compile specified module
# Copyright (C) 2020 CESNET z. s. p. o.
# Author(s): Jan Kubalek <kubalek@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=EVENT_COUNTER
#SYNTH=quartus

#export CLK_PERIOD=4.0
#export DEVICE=STRATIX10

all: comp

include ../../../../../build/Makefile

.PHONY: all
