# Makefile: Makefile to compile single module
# Copyright (C) 2025 CESNET z. s. p. o.
# Author(s): Tomas Hak <hak@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=PRIORITY_ENC
SYNTH=quartus

.PHONY: all
all: comp

include ../../../../../../../../../../../build/Makefile
