# Makefile: Makefile to compile specified module
# Copyright (C) 2020 CESNET
# Author: Martin Spinler <spinler@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

# Specify top level entity & architecture
TOP_LEVEL_ENT=SDP_URAM_XILINX

# Define targets
.PHONY: all
all: comp

include ../../../../../build/Makefile
