# Makefile: Makefile to compile module
# Copyright (C) 2025 CESNET
# Author: Daniel Kondys <kondys@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=FREQUENCY_METER
SYNTH=quartus

all: comp
include ../../../../../build/Makefile
.PHONY: all
