# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Daniel Kriz <xkrizd01@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=PCIE_CQ_AXI2MFB

.PHONY: all
all: comp

include ../../../../../build/Makefile
