# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2025 CESNET z. s. p. o
# Author(s): Ondrej Schwarz <ondrejschwarz@cesnet.cz>

TOP_LEVEL_ENT=SPOOKYHASH

SYNTH=quartus
export DEVICE=AGILEX

.PHONY: all
all: comp

include ../../../../../build/Makefile
