# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=RX_MAC_LITE_BUFFER

CLK_PORTS=RX_CLK TX_CLK
CLK_PERIOD=3.0 2.0

.PHONY: all
all: comp

include ../../../../../../../build/Makefile
