# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=PTC_FRAME_ERASER_UPTO96BITS

.PHONY: all
all: comp

include ../../../../../../build/Makefile
