# Makefile: Makefile script to compile specified module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MI_ASYNC
#SYNTH=quartus

#DEVICE=ULTRASCALE
CLK_PORTS=CLK_M CLK_S
CLK_PERIOD=4 5

.PHONY: all
all: comp

include ../../../../build/Makefile
