# Makefile: Makefile to compile module
# Copyright (C) 2023 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=APP_BIFLOW_SIMPLE_TOP
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=AGILEX

all: comp
include ../../../../../../../ofm/build/Makefile
.PHONY: all
