# Makefile: Makefile to compile single module
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): David Vodak <vodak@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXIS_PACKET_LEN
SYNTH=quartus

.PHONY: all
all: comp

include ../../../../../build/Makefile
