# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=DMA_ASFIFO_LUT

CLK_PORTS=WR_CLK RD_CLK
CLK_PERIOD=3 7.7

.PHONY: all
all: comp

include ../../../../../build/Makefile
