# Makefile: Makefile script to compile specified module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s):Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=GEN_REG_ARRAY
#SYNTH=quartus

export CLK_PERIOD=2.5
#export DEVICE=STRATIX10

all: comp

include ../../../../../build/Makefile

.PHONY: all
