# Makefile: Makefile script to compile specified module
# Copyright (C) DynaNIC Semiconductors, Ltd.
# Author(s): Vlastimil Kosar <kosar@dyna-nic.com>, 2026
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXI_PIPE
SYNTH=quartus

export CLK_PERIOD=4.0
export DEVICE=AGILEX

all: comp

include ../../../../../build/Makefile

.PHONY: all
