# Makefile: Makefile to compile module
# Copyright (C) 2024 CESNET
# Author: Daniel Kondys <kondys@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MVB_ITEM_COLLISION_RESOLVER
SYNTH=quartus

all: comp
include ../../../../../build/Makefile
.PHONY: all
