# Makefile: Build configuration of the AXI-AVMM bridge cocotb test
# Copyright (C) DynaNIC Semiconductors, Ltd.
# Author: David Beneš <benes@dyna-nic.com>, 2026
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=AXI2AVMM_BRIDGE
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
