# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MFB_CHECKSUM_L3L4
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
