# Makefile: Makefile to compile MFB Frame Masker
# Copyright (C) 2023 CESNET
# Author: Daniel Kondys <kondys@cesnet.cz>

TOP_LEVEL_ENT=MFB_FRAME_MASKER
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

.PHONY: all
all: comp

include ../../../../../build/Makefile
