# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2026 Dynanic Semiconductors Ltd.
# Author(s): David Beneš benes@dyna-nic.com>

TOP_LEVEL_ENT=MVB2AXIS
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
