# Makefile: Makefile to compile module
# Copyright (C) 2024 CESNET z. s. p. o.
# Author(s): Ondřej Schwarz <OndrejSchwarz@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MP_BRAM
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
