# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2025 CESNET z. s. p. o.
# Author(s): Ondrej Schwarz <ondrejschwarz@cesnet.cz>

SETTINGS = {
    "default" : { # The default setting of verification
        "DATA_WIDTH"   : "1",
        "WRITE_PORTS"  : "1",
        "READ_PORTS"   : "1",
        "BLOCK_ENABLE" : "False",
        "BLOCK_WIDTH"  : "8"
    },
    "aligned_data_width1": {
        "DATA_WIDTH": "8",
    },
    "aligned_data_width2": {
        "DATA_WIDTH": "16",
    },
    "aligned_data_width3": {
        "DATA_WIDTH": "32",
    },
    "unaligned_data_width1": {
        "DATA_WIDTH": "9",
    },
    "unaligned_data_width2": {
        "DATA_WIDTH": "18",
    },
    "unaligned_data_width3": {
        "DATA_WIDTH": "27",
    },
    "multiple_read_ports1": {
        "READ_PORTS": "2",
    },
    "multiple_read_ports2": {
        "READ_PORTS": "4",
    },
    "multiple_write_ports1": {
        "WRITE_PORTS": "2",
    },
    "multiple_write_ports2": {
        "WRITE_PORTS": "4",
    },
    "block_enable_8b_blocks": {
        "BLOCK_ENABLE" : "True",
        "BLOCK_WIDTH"  : "8"
    },
    "block_enable_9b_blocks": {
        "BLOCK_ENABLE" : "True",
        "BLOCK_WIDTH"  : "9"
    },
    "_combinations_" : (
    (), # Works the same as '("default",),' as the "default" is applied in every combination
    ("aligned_data_width1"),
    ("aligned_data_width2"),
    ("aligned_data_width3"),
    ("unaligned_data_width1"),
    ("unaligned_data_width2"),
    ("unaligned_data_width3"),
    ("multiple_read_ports1"),
    ("multiple_read_ports2"),
    ("multiple_write_ports1"),
    ("multiple_write_ports2"),
    ("aligned_data_width1", "block_enable_8b_blocks"),
    ("aligned_data_width2", "block_enable_8b_blocks"),
    ("aligned_data_width3", "block_enable_8b_blocks"),
    ("unaligned_data_width1", "block_enable_9b_blocks"),
    ("unaligned_data_width2", "block_enable_9b_blocks"),
    ("unaligned_data_width3", "block_enable_9b_blocks"),

    ("aligned_data_width1","multiple_read_ports1"),
    ("aligned_data_width1","multiple_read_ports2"),
    ("aligned_data_width1","multiple_write_ports1"),
    ("aligned_data_width1","multiple_write_ports2"),
    ("aligned_data_width1","multiple_read_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_read_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_write_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_read_ports1", "multiple_write_ports1"),
    ("aligned_data_width1","multiple_read_ports2", "multiple_write_ports2"),
    ("aligned_data_width1","multiple_read_ports2", "multiple_write_ports1"),
    ("aligned_data_width1","multiple_read_ports1", "multiple_write_ports2"),
    ("aligned_data_width1","multiple_read_ports1", "multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_read_ports2", "multiple_write_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_read_ports2", "multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width1","multiple_read_ports1", "multiple_write_ports2", "block_enable_8b_blocks"),

    ("aligned_data_width2","multiple_read_ports1"),
    ("aligned_data_width2","multiple_read_ports2"),
    ("aligned_data_width2","multiple_write_ports1"),
    ("aligned_data_width2","multiple_write_ports2"),
    ("aligned_data_width2","multiple_read_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_read_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_write_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_read_ports1", "multiple_write_ports1"),
    ("aligned_data_width2","multiple_read_ports2", "multiple_write_ports2"),
    ("aligned_data_width2","multiple_read_ports2", "multiple_write_ports1"),
    ("aligned_data_width2","multiple_read_ports1", "multiple_write_ports2"),
    ("aligned_data_width2","multiple_read_ports1", "multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_read_ports2", "multiple_write_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_read_ports2", "multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width2","multiple_read_ports1", "multiple_write_ports2", "block_enable_8b_blocks"),

    ("aligned_data_width3","multiple_read_ports1"),
    ("aligned_data_width3","multiple_read_ports2"),
    ("aligned_data_width3","multiple_write_ports1"),
    ("aligned_data_width3","multiple_write_ports2"),
    ("aligned_data_width3","multiple_read_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_read_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_write_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_read_ports1", "multiple_write_ports1"),
    ("aligned_data_width3","multiple_read_ports2", "multiple_write_ports2"),
    ("aligned_data_width3","multiple_read_ports2", "multiple_write_ports1"),
    ("aligned_data_width3","multiple_read_ports1", "multiple_write_ports2"),
    ("aligned_data_width3","multiple_read_ports1", "multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_read_ports2", "multiple_write_ports2", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_read_ports2", "multiple_write_ports1", "block_enable_8b_blocks"),
    ("aligned_data_width3","multiple_read_ports1", "multiple_write_ports2", "block_enable_8b_blocks"),

    ("unaligned_data_width1","multiple_read_ports1"),
    ("unaligned_data_width1","multiple_read_ports2"),
    ("unaligned_data_width1","multiple_write_ports1"),
    ("unaligned_data_width1","multiple_write_ports2"),
    ("unaligned_data_width1","multiple_read_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_read_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_write_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_read_ports1", "multiple_write_ports1"),
    ("unaligned_data_width1","multiple_read_ports2", "multiple_write_ports2"),
    ("unaligned_data_width1","multiple_read_ports2", "multiple_write_ports1"),
    ("unaligned_data_width1","multiple_read_ports1", "multiple_write_ports2"),
    ("unaligned_data_width1","multiple_read_ports1", "multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_read_ports2", "multiple_write_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_read_ports2", "multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width1","multiple_read_ports1", "multiple_write_ports2", "block_enable_9b_blocks"),

    ("unaligned_data_width2","multiple_read_ports1"),
    ("unaligned_data_width2","multiple_read_ports2"),
    ("unaligned_data_width2","multiple_write_ports1"),
    ("unaligned_data_width2","multiple_write_ports2"),
    ("unaligned_data_width2","multiple_read_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_read_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_write_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_read_ports1", "multiple_write_ports1"),
    ("unaligned_data_width2","multiple_read_ports2", "multiple_write_ports2"),
    ("unaligned_data_width2","multiple_read_ports2", "multiple_write_ports1"),
    ("unaligned_data_width2","multiple_read_ports1", "multiple_write_ports2"),
    ("unaligned_data_width2","multiple_read_ports1", "multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_read_ports2", "multiple_write_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_read_ports2", "multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width2","multiple_read_ports1", "multiple_write_ports2", "block_enable_9b_blocks"),

    ("unaligned_data_width3","multiple_read_ports1"),
    ("unaligned_data_width3","multiple_read_ports2"),
    ("unaligned_data_width3","multiple_write_ports1"),
    ("unaligned_data_width3","multiple_write_ports2"),
    ("unaligned_data_width3","multiple_read_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_read_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_write_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_read_ports1", "multiple_write_ports1"),
    ("unaligned_data_width3","multiple_read_ports2", "multiple_write_ports2"),
    ("unaligned_data_width3","multiple_read_ports2", "multiple_write_ports1"),
    ("unaligned_data_width3","multiple_read_ports1", "multiple_write_ports2"),
    ("unaligned_data_width3","multiple_read_ports1", "multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_read_ports2", "multiple_write_ports2", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_read_ports2", "multiple_write_ports1", "block_enable_9b_blocks"),
    ("unaligned_data_width3","multiple_read_ports1", "multiple_write_ports2", "block_enable_9b_blocks"),
    ),
}
