# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MI_SPLITTER

#SYNTH=quartus
export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

all: comp
include ../../../../build/Makefile
.PHONY: all
