# Makefile: Makefile for lvt_mem.vhd
# Copyright (C) 2024 CESNET z. s. p. o.
# Author(s): Oliver Gurka <oliver.gurka@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=LVT_MEM
SYNTH=quartus

export CLK_PERIOD=5.0
export DEVICE=AGILEX

all: comp

include ../../../../../build/Makefile

.PHONY: all
