# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Tomas Hak <xhakto01@stud.fit.vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=SDM_CLIENT

#SYNTH=quartus
export CLK_PERIOD=4.0

all: comp
include ../../../../build/Makefile
.PHONY: all
