# Makefile: Makefile to compile module
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=PCIE_TELEMETRY_MI
SYNTH=quartus
export DEVICE=AGILEX

all: comp
include ../../../../../build/Makefile
.PHONY: all
