package require -exact qsys 21.3

array set PARAMS $IP_PARAMS_L
source $PARAMS(CORE_BASE)/src/ip/common.tcl

# create the system "ftile_mr_eth_ip"
proc do_create_ftile_mr_eth_ip {device family ipname filename} {
	# create the system
	create_system $ipname
	set_project_property DEVICE $device
	set_project_property DEVICE_FAMILY $family
	set_project_property HIDE_FROM_IP_CATALOG {true}
	set_use_testbench_naming_pattern 0 {}

	# add HDL parameters

	# add the components
	add_instance eth_f_dr_0 eth_f_dr
	set_instance_parameter_value eth_f_dr_0 {CLIENT_INT_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {DEV_BOARD} {1}
	set_instance_parameter_value eth_f_dr_0 {ENABLE_ADME_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {ENABLE_ANLT_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {ENABLE_CWBIN_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {ENABLE_ETK_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {ENABLE_PTP_DEBUG} {0}
	set_instance_parameter_value eth_f_dr_0 {ENABLE_PTP_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_40GE_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P0_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P10_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P11_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P12_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P13_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P14_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P15_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P16_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P17_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P18_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P19_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P1_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P20_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P21_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P22_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P23_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P24_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P25_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P26_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P27_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P28_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P29_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P2_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P30_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P31_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P32_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P3_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P4_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P5_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P6_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P7_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P8_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {EN_FHT_PRECODE_P9_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P10_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P11_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P12_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P13_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P14_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P15_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P16_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P17_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P18_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P19_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P1_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P20_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P21_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P22_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P23_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P24_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P25_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P26_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P27_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P28_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P29_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P2_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P30_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P31_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P32_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P3_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P4_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P5_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P6_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P7_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P8_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {ETH_MODE_P9_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {GEN_SYNTH} {1}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P10_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P11_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P12_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P13_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P14_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P15_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P16_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P17_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P18_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P19_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P1_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P20_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P21_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P22_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P23_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P24_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P25_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P26_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P27_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P28_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P29_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P2_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P30_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P31_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P32_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P3_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P4_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P5_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P6_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P7_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P8_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {MAC_P0_COPY_P9_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {NO_OF_INST} {1}
	set_instance_parameter_value eth_f_dr_0 {NUM_SEC_PROFILE_GUI} {1}
	set_instance_parameter_value eth_f_dr_0 {P0_START_PROF_NO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {P1_START_PROF_NO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {P2_START_PROF_NO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {P3_START_PROF_NO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {PACKING_EN_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {PHY_REFCLK_GUI} {156.250000}
	set_instance_parameter_value eth_f_dr_0 {PTP_ACC_MODE_GUI} {1}
	set_instance_parameter_value eth_f_dr_0 {PTP_FP_WIDTH_GUI} {8}
	set_instance_parameter_value eth_f_dr_0 {PTP_LOGIC_RES_OPT_GUI} {3}
	set_instance_parameter_value eth_f_dr_0 {RCFG_GRP_GUI} {25G-1}
	set_instance_parameter_value eth_f_dr_0 {REFCLK_CWBIN_GUI} {100.0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P0_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P10_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P11_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P12_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P13_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P14_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P15_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P16_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P17_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P18_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P19_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P1_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P20_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P21_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P22_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P23_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P24_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P25_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P26_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P27_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P28_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P29_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P2_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P30_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P31_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P32_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P3_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P4_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P5_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P6_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P7_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P8_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {RSFEC_TYPE_P9_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P10_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P11_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P12_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P13_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P14_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P15_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P16_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P17_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P18_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P19_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P1_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P20_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P21_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P22_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P23_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P24_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P25_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P26_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P27_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P28_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P29_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P2_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P30_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P31_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P32_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P3_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P4_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P5_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P6_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P7_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P8_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SEC_P9_PORTNO_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {SIP_TAG} {1}
	set_instance_parameter_value eth_f_dr_0 {START_PROF_GUI} {1x25GE-1/10GE-1}
	set_instance_parameter_value eth_f_dr_0 {SYSPLL_CUSTOM_GUI} {830.078125}
	set_instance_parameter_value eth_f_dr_0 {SYSPLL_RATE_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {XCVR_TYPE_GUI} {0}
	set_instance_parameter_value eth_f_dr_0 {enable_async_adapters_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p0_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p0_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p0_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p0_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p0_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p0_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p0_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p0_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p0_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p10_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p10_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p10_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p10_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p10_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p10_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p10_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p10_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p10_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p10_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p11_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p11_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p11_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p11_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p11_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p11_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p11_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p11_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p11_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p11_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p12_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p12_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p12_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p12_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p12_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p12_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p12_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p12_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p12_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p12_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p13_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p13_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p13_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p13_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p13_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p13_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p13_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p13_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p13_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p13_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p14_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p14_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p14_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p14_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p14_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p14_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p14_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p14_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p14_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p14_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p15_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p15_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p15_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p15_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p15_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p15_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p15_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p15_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p15_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p15_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p16_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p16_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p16_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p16_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p16_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p16_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p16_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p16_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p16_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p16_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p17_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p17_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p17_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p17_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p17_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p17_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p17_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p17_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p17_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p17_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p18_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p18_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p18_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p18_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p18_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p18_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p18_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p18_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p18_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p18_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p19_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p19_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p19_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p19_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p19_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p19_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p19_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p19_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p19_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p19_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p1_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p1_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p1_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p1_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p1_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p1_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p1_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p1_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p1_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p1_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p20_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p20_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p20_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p20_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p20_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p20_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p20_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p20_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p20_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p20_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p21_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p21_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p21_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p21_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p21_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p21_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p21_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p21_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p21_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p21_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p22_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p22_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p22_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p22_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p22_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p22_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p22_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p22_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p22_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p22_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p23_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p23_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p23_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p23_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p23_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p23_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p23_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p23_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p23_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p23_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p24_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p24_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p24_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p24_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p24_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p24_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p24_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p24_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p24_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p24_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p25_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p25_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p25_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p25_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p25_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p25_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p25_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p25_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p25_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p25_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p26_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p26_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p26_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p26_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p26_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p26_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p26_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p26_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p26_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p26_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p27_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p27_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p27_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p27_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p27_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p27_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p27_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p27_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p27_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p27_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p28_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p28_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p28_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p28_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p28_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p28_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p28_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p28_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p28_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p28_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p29_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p29_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p29_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p29_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p29_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p29_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p29_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p29_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p29_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p29_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p2_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p2_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p2_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p2_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p2_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p2_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p2_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p2_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p2_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p2_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p30_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p30_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p30_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p30_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p30_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p30_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p30_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p30_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p30_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p30_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p31_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p31_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p31_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p31_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p31_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p31_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p31_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p31_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p31_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p31_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p32_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p32_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p32_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p32_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p32_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p32_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p32_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p32_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p32_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p32_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p3_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p3_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p3_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p3_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p3_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p3_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p3_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p3_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p3_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p3_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p4_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p4_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p4_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p4_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p4_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p4_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p4_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p4_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p4_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p4_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p5_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p5_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p5_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p5_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p5_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p5_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p5_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p5_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p5_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p5_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p6_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p6_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p6_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p6_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p6_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p6_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p6_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p6_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p6_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p6_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p7_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p7_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p7_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p7_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p7_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p7_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p7_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p7_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p7_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p7_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p8_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p8_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p8_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p8_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p8_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p8_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p8_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p8_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p8_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p8_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {p9_additional_ipg_removed_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_enforce_max_frame_size_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_flow_control_gui} {No}
	set_instance_parameter_value eth_f_dr_0 {p9_forward_rx_pause_requests_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_link_fault_mode_gui} {Off}
	set_instance_parameter_value eth_f_dr_0 {p9_preamble_passthrough_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_rx_bytes_to_remove_gui} {Remove CRC bytes}
	set_instance_parameter_value eth_f_dr_0 {p9_rx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p9_rx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p9_source_address_insertion_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_strict_preamble_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_strict_sfd_checking_gui} {0}
	set_instance_parameter_value eth_f_dr_0 {p9_tx_ipg_size_gui} {12}
	set_instance_parameter_value eth_f_dr_0 {p9_tx_max_frame_size_gui} {1518}
	set_instance_parameter_value eth_f_dr_0 {p9_tx_vlan_detection_gui} {1}
	set_instance_parameter_value eth_f_dr_0 {p9_txmac_saddr_gui} {73588229205}
	set_instance_parameter_value eth_f_dr_0 {ready_latency_gui} {0}
	set_instance_property eth_f_dr_0 AUTO_EXPORT true

	# add wirelevel expressions

	# preserve ports for debug

	# add the exports
	set_interface_property i_tx_clk EXPORT_OF eth_f_dr_0.i_tx_clk
	set_interface_property i_rx_clk EXPORT_OF eth_f_dr_0.i_rx_clk
	set_interface_property o_clk_pll EXPORT_OF eth_f_dr_0.o_clk_pll
	set_interface_property o_sys_pll_locked EXPORT_OF eth_f_dr_0.o_sys_pll_locked
	set_interface_property i_reconfig_clk EXPORT_OF eth_f_dr_0.i_reconfig_clk
	set_interface_property i_reconfig_reset EXPORT_OF eth_f_dr_0.i_reconfig_reset
	set_interface_property serial EXPORT_OF eth_f_dr_0.serial
	set_interface_property i_clk_ref EXPORT_OF eth_f_dr_0.i_clk_ref
	set_interface_property i_clk_sys EXPORT_OF eth_f_dr_0.i_clk_sys
	set_interface_property o_p0_clk_tx_div EXPORT_OF eth_f_dr_0.o_p0_clk_tx_div
	set_interface_property o_p0_clk_rec_div64 EXPORT_OF eth_f_dr_0.o_p0_clk_rec_div64
	set_interface_property o_p0_clk_rec_div EXPORT_OF eth_f_dr_0.o_p0_clk_rec_div
	set_interface_property i_p0_rst_n EXPORT_OF eth_f_dr_0.i_p0_rst_n
	set_interface_property i_p0_tx_rst_n EXPORT_OF eth_f_dr_0.i_p0_tx_rst_n
	set_interface_property i_p0_rx_rst_n EXPORT_OF eth_f_dr_0.i_p0_rx_rst_n
	set_interface_property o_p0_rst_ack_n EXPORT_OF eth_f_dr_0.o_p0_rst_ack_n
	set_interface_property o_p0_rx_rst_ack_n EXPORT_OF eth_f_dr_0.o_p0_rx_rst_ack_n
	set_interface_property o_p0_tx_rst_ack_n EXPORT_OF eth_f_dr_0.o_p0_tx_rst_ack_n
	set_interface_property o_p0_tx_pll_locked EXPORT_OF eth_f_dr_0.o_p0_tx_pll_locked
	set_interface_property o_p0_cdr_lock EXPORT_OF eth_f_dr_0.o_p0_cdr_lock
	set_interface_property o_p0_tx_lanes_stable EXPORT_OF eth_f_dr_0.o_p0_tx_lanes_stable
	set_interface_property o_p0_rx_pcs_ready EXPORT_OF eth_f_dr_0.o_p0_rx_pcs_ready
	set_interface_property p0_pfc_ports EXPORT_OF eth_f_dr_0.p0_pfc_ports
	set_interface_property p0_status_ports EXPORT_OF eth_f_dr_0.p0_status_ports
	set_interface_property p0_reconfig_eth_slave EXPORT_OF eth_f_dr_0.p0_reconfig_eth_slave
	set_interface_property i_clk_pll EXPORT_OF eth_f_dr_0.i_clk_pll
	set_interface_property p0_ptp_clk_tx_tod EXPORT_OF eth_f_dr_0.p0_ptp_clk_tx_tod
	set_interface_property p0_ptp_clk_rx_tod EXPORT_OF eth_f_dr_0.p0_ptp_clk_rx_tod
	set_interface_property reconfig_xcvr_slave_0 EXPORT_OF eth_f_dr_0.reconfig_xcvr_slave_0
	set_interface_property tx_mac_seg EXPORT_OF eth_f_dr_0.tx_mac_seg
	set_interface_property rx_mac_seg EXPORT_OF eth_f_dr_0.rx_mac_seg

	# set values for exposed HDL parameters

	# set the the module properties
	set_module_property BONUS_DATA {<?xml version="1.0" encoding="UTF-8"?>
<bonusData>
 <element __value="eth_f_dr_0">
  <datum __value="_sortIndex" value="0" type="int" />
 </element>
</bonusData>
}
	set_module_property FILE {$filename}
	set_module_property GENERATION_ID {0x00000000}
	set_module_property NAME {$ipname}

	# save the system
	sync_sysinfo_parameters
	save_system $ipname
}

proc do_set_exported_interface_sysinfo_parameters {} {
}

# create all the systems, from bottom up
do_create_ftile_mr_eth_ip $PARAMS(IP_DEVICE) $PARAMS(IP_DEVICE_FAMILY) $PARAMS(IP_COMP_NAME) [get_ip_filename $PARAMS(IP_COMP_NAME)]

# set system info parameters on exported interface, from bottom up
do_set_exported_interface_sysinfo_parameters
