# Makefile: Makefile script to compile specified module
# Copyright (C) 2024 CESNET z. s. p. o.
# Author:   David Beneš <xbenes52@vutbr.cz>

# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=FRAME_PACKER
SYNTH=vivado
export DEVICE=AGILEX
all: comp

include ../../../../../build/Makefile

.PHONY: all
