# Makefile: Makefile to compile module
# Copyright (C) 2024 CESNET z. s. p. o.
# Author(s): David Beneš <xbenes52@vutbr.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=mfb_pipe
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
