# Makefile: Makefile to compile module
# Copyright (C) 2019 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#

TOP_LEVEL_ENT=MFB_SHREG
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE

all: comp
include ../../../../../build/Makefile
.PHONY: all
