# Makefile: Makefile to compile module
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Tomas Hak <xhakto01@vut.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=RATE_LIMITER
SYNTH=quartus
#export CLK_PERIOD=4.0
#export DEVICE=ULTRASCALE
# export DEVICE=AGILEX

all: comp
include ../../../../../../ofm/build/Makefile
.PHONY: all

