# Makefile: Makefile script to compile specified module
# Copyright (C) 2021 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=SDP_BRAM

#SYNTH=quartus
#DEVICE=AGILEX
CLK_PORTS=WR_CLK RD_CLK
CLK_PERIOD=4.1 3

.PHONY: all
all: comp

include ../../../../../build/Makefile
