# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2026 CESNET z. s. p. o.
# Author(s): Tomáš Neckař <xneckat00@stud.fit.vut.cz>

TOP_LEVEL_ENT=AXIS_VECTOR2PACKET

SYNTH=quartus
export DEVICE=AGILEX

CLK_PORTS=CLK
CLK_PERIOD=5.0

.PHONY: all
all: comp

include ../../../../../build/Makefile
