# Makefile: Makefile to compile module
# Copyright (C) 2025 CESNET z. s. p. o.
# Author(s): Daniel Kondys <kondys@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=MFB_MVB_PREPENDER
TARGET=cocotb

.PHONY: all
all: comp

include ../../../../../build/Makefile
