# ver_settings.py:  Verification settings
# Copyright (C) 2024 DynaNIC Semiconductors, Ltd.
# Author(s): Radek Hajek <hajek@dyna-nic.com>
#
# SPDX-License-Identifier: BSD-3-Clause

SETTINGS = {
    "default" : { # The default setting of verification
        "REGIONS"            : "1",
        "REGION_SIZE"        : "4",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "256",
        "USE_IN_PIPE"        : "0",
        "USE_OUT_PIPE"       : "0",
    },
    "mfb_1_1_8_8" : {
        "REGIONS"            : "1",
        "REGION_SIZE"        : "1",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "64",
    },
    "mfb_1_1_8_16" : {
        "REGIONS"            : "1",
        "REGION_SIZE"        : "1",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "16",
        "AXI_DATA_WIDTH"     : "128",
    },
    "mfb_1_1_8_24" : {
        "REGIONS"            : "1",
        "REGION_SIZE"        : "1",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "24",
        "AXI_DATA_WIDTH"     : "192",
    },
    "mfb_1_8_8_8" : {
        "REGIONS"            : "1",
        "REGION_SIZE"        : "8",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "512",
    },
    "mfb_1_8_32_8" : {
        "REGIONS"            : "1",
        "REGION_SIZE"        : "8",
        "BLOCK_SIZE"         : "32",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "2048",
    },
    "mfb_1_2_4_8" : {
        "REGIONS"            : "1",
        "REGION_SIZE"        : "2",
        "BLOCK_SIZE"         : "4",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "64",
    },
    "mfb_2_8_8_8" : {
        "REGIONS"            : "2",
        "REGION_SIZE"        : "8",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "1024",
    },
    "mfb_4_4_8_8" : {
        "REGIONS"            : "4",
        "REGION_SIZE"        : "4",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "1024",
    },
    "mfb_4_4_8_16" : {
        "REGIONS"            : "4",
        "REGION_SIZE"        : "4",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "16",
        "AXI_DATA_WIDTH"     : "2048",
    },
    "mfb_3_4_8_8" : {
        "REGIONS"            : "3",
        "REGION_SIZE"        : "4",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "768",
    },
    "mfb_3_4_8_16" : {
        "REGIONS"            : "3",
        "REGION_SIZE"        : "4",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "16",
        "AXI_DATA_WIDTH"     : "1536",
    },
    "mfb_4_8_8_8" : {
        "REGIONS"            : "4",
        "REGION_SIZE"        : "8",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "8",
        "AXI_DATA_WIDTH"     : "2048",
    },
    "mfb_2_1_8_32" : {
        "REGIONS"            : "2",
        "REGION_SIZE"        : "1",
        "BLOCK_SIZE"         : "8",
        "ITEM_WIDTH"         : "32",
        "AXI_DATA_WIDTH"     : "512",
    },
    "mfb_2_1_1_32" : {
        "REGIONS"            : "2",
        "REGION_SIZE"        : "1",
        "BLOCK_SIZE"         : "1",
        "ITEM_WIDTH"         : "32",
        "AXI_DATA_WIDTH"     : "64",
    },
    "pipe_in" : {
        "USE_IN_PIPE"        : "1",
    },
    "pipe_out" : {
        "USE_OUT_PIPE"       : "1",
    },
    "_combinations_" : (
    (), # Works the same as '("default",),' as the "default" is applied in every combination
    ("pipe_in",),
    ("pipe_out",),
    ("pipe_in","pipe_out",),
    ("mfb_1_1_8_8",),
    ("mfb_1_1_8_16",),
    ("mfb_1_1_8_24",),
    ("mfb_1_8_8_8",),
    ("mfb_1_8_32_8",),
    ("mfb_1_2_4_8",),
    ("mfb_2_8_8_8",),
    ("mfb_4_4_8_8",),
    ("mfb_4_4_8_16",),
    ("mfb_3_4_8_8",),
    ("mfb_3_4_8_16",),
    ("mfb_4_8_8_8",),
    ("mfb_4_8_8_8","pipe_in","pipe_out",),
    ("mfb_2_1_8_32",),
    ("mfb_2_1_8_32","pipe_in","pipe_out",),
    ("mfb_2_1_1_32",),
    ),
}
